/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddLinkRequest,
  AddShowRequest,
  ErrorResponse,
  HomeRecommendations,
  Link,
  LinkList,
  ListTrackedParams,
  Settings,
  TrackedShow,
  TrackedShowList,
  UpdateLinkRequest,
  UpdateSettingsRequest,
  UpdateShowRequest,
  UserShow
} from './model';

import { customInstance } from '../http';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List the user's tracked shows with progress
 */
export const listTracked = (
    params?: ListTrackedParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TrackedShowList>(
      {url: `/me/shows`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListTrackedQueryKey = (params?: ListTrackedParams,) => {
    return [
    `/me/shows`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTrackedQueryOptions = <TData = Awaited<ReturnType<typeof listTracked>>, TError = ErrorResponse>(params?: ListTrackedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTracked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTrackedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTracked>>> = ({ signal }) => listTracked(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTracked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTrackedQueryResult = NonNullable<Awaited<ReturnType<typeof listTracked>>>
export type ListTrackedQueryError = ErrorResponse


export function useListTracked<TData = Awaited<ReturnType<typeof listTracked>>, TError = ErrorResponse>(
 params: undefined |  ListTrackedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTracked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTracked>>,
          TError,
          Awaited<ReturnType<typeof listTracked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTracked<TData = Awaited<ReturnType<typeof listTracked>>, TError = ErrorResponse>(
 params?: ListTrackedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTracked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTracked>>,
          TError,
          Awaited<ReturnType<typeof listTracked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTracked<TData = Awaited<ReturnType<typeof listTracked>>, TError = ErrorResponse>(
 params?: ListTrackedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTracked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the user's tracked shows with progress
 */

export function useListTracked<TData = Awaited<ReturnType<typeof listTracked>>, TError = ErrorResponse>(
 params?: ListTrackedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTracked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTrackedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Track a show (imports from TMDB on first use)
 */
export const addShow = (
    addShowRequest: AddShowRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserShow>(
      {url: `/me/shows`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addShowRequest, signal
    },
      options);
    }




export const getAddShowQueryKey = (addShowRequest?: AddShowRequest,) => {
    return [
    'POST', `/me/shows`, addShowRequest
    ] as const;
    }


export const getAddShowQueryOptions = <TData = Awaited<ReturnType<typeof addShow>>, TError = ErrorResponse>(addShowRequest: AddShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAddShowQueryKey(addShowRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof addShow>>> = ({ signal }) => addShow(addShowRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof addShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddShowQueryResult = NonNullable<Awaited<ReturnType<typeof addShow>>>
export type AddShowQueryError = ErrorResponse


export function useAddShow<TData = Awaited<ReturnType<typeof addShow>>, TError = ErrorResponse>(
 addShowRequest: AddShowRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof addShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof addShow>>,
          TError,
          Awaited<ReturnType<typeof addShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddShow<TData = Awaited<ReturnType<typeof addShow>>, TError = ErrorResponse>(
 addShowRequest: AddShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof addShow>>,
          TError,
          Awaited<ReturnType<typeof addShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddShow<TData = Awaited<ReturnType<typeof addShow>>, TError = ErrorResponse>(
 addShowRequest: AddShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Track a show (imports from TMDB on first use)
 */

export function useAddShow<TData = Awaited<ReturnType<typeof addShow>>, TError = ErrorResponse>(
 addShowRequest: AddShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAddShowQueryOptions(addShowRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary One tracked show with progress
 */
export const getTracked = (
    showId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TrackedShow>(
      {url: `/me/shows/${showId}`, method: 'GET', signal
    },
      options);
    }




export const getGetTrackedQueryKey = (showId: number,) => {
    return [
    `/me/shows/${showId}`
    ] as const;
    }


export const getGetTrackedQueryOptions = <TData = Awaited<ReturnType<typeof getTracked>>, TError = ErrorResponse>(showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrackedQueryKey(showId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTracked>>> = ({ signal }) => getTracked(showId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTracked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrackedQueryResult = NonNullable<Awaited<ReturnType<typeof getTracked>>>
export type GetTrackedQueryError = ErrorResponse


export function useGetTracked<TData = Awaited<ReturnType<typeof getTracked>>, TError = ErrorResponse>(
 showId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTracked>>,
          TError,
          Awaited<ReturnType<typeof getTracked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTracked<TData = Awaited<ReturnType<typeof getTracked>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTracked>>,
          TError,
          Awaited<ReturnType<typeof getTracked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTracked<TData = Awaited<ReturnType<typeof getTracked>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary One tracked show with progress
 */

export function useGetTracked<TData = Awaited<ReturnType<typeof getTracked>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrackedQueryOptions(showId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Update status/favorite/dubbing
 */
export const updateShow = (
    showId: number,
    updateShowRequest: UpdateShowRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserShow>(
      {url: `/me/shows/${showId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateShowRequest, signal
    },
      options);
    }




export const getUpdateShowQueryKey = (showId: number,
    updateShowRequest?: UpdateShowRequest,) => {
    return [
    'PATCH', `/me/shows/${showId}`, updateShowRequest
    ] as const;
    }


export const getUpdateShowQueryOptions = <TData = Awaited<ReturnType<typeof updateShow>>, TError = ErrorResponse>(showId: number,
    updateShowRequest: UpdateShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateShowQueryKey(showId,updateShowRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateShow>>> = ({ signal }) => updateShow(showId,updateShowRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateShowQueryResult = NonNullable<Awaited<ReturnType<typeof updateShow>>>
export type UpdateShowQueryError = ErrorResponse


export function useUpdateShow<TData = Awaited<ReturnType<typeof updateShow>>, TError = ErrorResponse>(
 showId: number,
    updateShowRequest: UpdateShowRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateShow>>,
          TError,
          Awaited<ReturnType<typeof updateShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateShow<TData = Awaited<ReturnType<typeof updateShow>>, TError = ErrorResponse>(
 showId: number,
    updateShowRequest: UpdateShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateShow>>,
          TError,
          Awaited<ReturnType<typeof updateShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateShow<TData = Awaited<ReturnType<typeof updateShow>>, TError = ErrorResponse>(
 showId: number,
    updateShowRequest: UpdateShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update status/favorite/dubbing
 */

export function useUpdateShow<TData = Awaited<ReturnType<typeof updateShow>>, TError = ErrorResponse>(
 showId: number,
    updateShowRequest: UpdateShowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateShowQueryOptions(showId,updateShowRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Stop tracking a show
 */
export const removeShow = (
    showId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/shows/${showId}`, method: 'DELETE', signal
    },
      options);
    }




export const getRemoveShowQueryKey = (showId: number,) => {
    return [
    'DELETE', `/me/shows/${showId}`
    ] as const;
    }


export const getRemoveShowQueryOptions = <TData = Awaited<ReturnType<typeof removeShow>>, TError = unknown>(showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof removeShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRemoveShowQueryKey(showId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof removeShow>>> = ({ signal }) => removeShow(showId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof removeShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RemoveShowQueryResult = NonNullable<Awaited<ReturnType<typeof removeShow>>>
export type RemoveShowQueryError = unknown


export function useRemoveShow<TData = Awaited<ReturnType<typeof removeShow>>, TError = unknown>(
 showId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof removeShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof removeShow>>,
          TError,
          Awaited<ReturnType<typeof removeShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRemoveShow<TData = Awaited<ReturnType<typeof removeShow>>, TError = unknown>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof removeShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof removeShow>>,
          TError,
          Awaited<ReturnType<typeof removeShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRemoveShow<TData = Awaited<ReturnType<typeof removeShow>>, TError = unknown>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof removeShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Stop tracking a show
 */

export function useRemoveShow<TData = Awaited<ReturnType<typeof removeShow>>, TError = unknown>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof removeShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRemoveShowQueryOptions(showId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Atomic and idempotent. Preserves existing episode ratings and watch dates. Episodes added to the catalog later are not automatically watched.
 * @summary Mark all catalogued episodes watched and set tracking status to completed
 */
export const watchShow = (
    showId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/shows/${showId}/watch`, method: 'POST', signal
    },
      options);
    }




export const getWatchShowQueryKey = (showId: number,) => {
    return [
    'POST', `/me/shows/${showId}/watch`
    ] as const;
    }


export const getWatchShowQueryOptions = <TData = Awaited<ReturnType<typeof watchShow>>, TError = ErrorResponse>(showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWatchShowQueryKey(showId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof watchShow>>> = ({ signal }) => watchShow(showId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof watchShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WatchShowQueryResult = NonNullable<Awaited<ReturnType<typeof watchShow>>>
export type WatchShowQueryError = ErrorResponse


export function useWatchShow<TData = Awaited<ReturnType<typeof watchShow>>, TError = ErrorResponse>(
 showId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof watchShow>>,
          TError,
          Awaited<ReturnType<typeof watchShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWatchShow<TData = Awaited<ReturnType<typeof watchShow>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof watchShow>>,
          TError,
          Awaited<ReturnType<typeof watchShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWatchShow<TData = Awaited<ReturnType<typeof watchShow>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark all catalogued episodes watched and set tracking status to completed
 */

export function useWatchShow<TData = Awaited<ReturnType<typeof watchShow>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWatchShowQueryOptions(showId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Mark an episode watched
 */
export const watchEpisode = (
    showId: number,
    episodeId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/shows/${showId}/episodes/${episodeId}/watch`, method: 'POST', signal
    },
      options);
    }




export const getWatchEpisodeQueryKey = (showId: number,
    episodeId: number,) => {
    return [
    'POST', `/me/shows/${showId}/episodes/${episodeId}/watch`
    ] as const;
    }


export const getWatchEpisodeQueryOptions = <TData = Awaited<ReturnType<typeof watchEpisode>>, TError = ErrorResponse>(showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchEpisode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWatchEpisodeQueryKey(showId,episodeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof watchEpisode>>> = ({ signal }) => watchEpisode(showId,episodeId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined && episodeId !== null && episodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof watchEpisode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WatchEpisodeQueryResult = NonNullable<Awaited<ReturnType<typeof watchEpisode>>>
export type WatchEpisodeQueryError = ErrorResponse


export function useWatchEpisode<TData = Awaited<ReturnType<typeof watchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchEpisode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof watchEpisode>>,
          TError,
          Awaited<ReturnType<typeof watchEpisode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWatchEpisode<TData = Awaited<ReturnType<typeof watchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchEpisode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof watchEpisode>>,
          TError,
          Awaited<ReturnType<typeof watchEpisode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWatchEpisode<TData = Awaited<ReturnType<typeof watchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchEpisode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark an episode watched
 */

export function useWatchEpisode<TData = Awaited<ReturnType<typeof watchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof watchEpisode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWatchEpisodeQueryOptions(showId,episodeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Mark an episode unwatched
 */
export const unwatchEpisode = (
    showId: number,
    episodeId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/shows/${showId}/episodes/${episodeId}/watch`, method: 'DELETE', signal
    },
      options);
    }




export const getUnwatchEpisodeQueryKey = (showId: number,
    episodeId: number,) => {
    return [
    'DELETE', `/me/shows/${showId}/episodes/${episodeId}/watch`
    ] as const;
    }


export const getUnwatchEpisodeQueryOptions = <TData = Awaited<ReturnType<typeof unwatchEpisode>>, TError = ErrorResponse>(showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unwatchEpisode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUnwatchEpisodeQueryKey(showId,episodeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof unwatchEpisode>>> = ({ signal }) => unwatchEpisode(showId,episodeId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined && episodeId !== null && episodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof unwatchEpisode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UnwatchEpisodeQueryResult = NonNullable<Awaited<ReturnType<typeof unwatchEpisode>>>
export type UnwatchEpisodeQueryError = ErrorResponse


export function useUnwatchEpisode<TData = Awaited<ReturnType<typeof unwatchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof unwatchEpisode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof unwatchEpisode>>,
          TError,
          Awaited<ReturnType<typeof unwatchEpisode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUnwatchEpisode<TData = Awaited<ReturnType<typeof unwatchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unwatchEpisode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof unwatchEpisode>>,
          TError,
          Awaited<ReturnType<typeof unwatchEpisode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUnwatchEpisode<TData = Awaited<ReturnType<typeof unwatchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unwatchEpisode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark an episode unwatched
 */

export function useUnwatchEpisode<TData = Awaited<ReturnType<typeof unwatchEpisode>>, TError = ErrorResponse>(
 showId: number,
    episodeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unwatchEpisode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUnwatchEpisodeQueryOptions(showId,episodeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary List reference links
 */
export const listLinks = (
    showId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<LinkList>(
      {url: `/me/shows/${showId}/links`, method: 'GET', signal
    },
      options);
    }




export const getListLinksQueryKey = (showId: number,) => {
    return [
    `/me/shows/${showId}/links`
    ] as const;
    }


export const getListLinksQueryOptions = <TData = Awaited<ReturnType<typeof listLinks>>, TError = ErrorResponse>(showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLinks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLinksQueryKey(showId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLinks>>> = ({ signal }) => listLinks(showId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLinksQueryResult = NonNullable<Awaited<ReturnType<typeof listLinks>>>
export type ListLinksQueryError = ErrorResponse


export function useListLinks<TData = Awaited<ReturnType<typeof listLinks>>, TError = ErrorResponse>(
 showId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLinks>>,
          TError,
          Awaited<ReturnType<typeof listLinks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLinks<TData = Awaited<ReturnType<typeof listLinks>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLinks>>,
          TError,
          Awaited<ReturnType<typeof listLinks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLinks<TData = Awaited<ReturnType<typeof listLinks>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLinks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List reference links
 */

export function useListLinks<TData = Awaited<ReturnType<typeof listLinks>>, TError = ErrorResponse>(
 showId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLinks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLinksQueryOptions(showId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Add a reference link
 */
export const addLink = (
    showId: number,
    addLinkRequest: AddLinkRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Link>(
      {url: `/me/shows/${showId}/links`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLinkRequest, signal
    },
      options);
    }




export const getAddLinkQueryKey = (showId: number,
    addLinkRequest?: AddLinkRequest,) => {
    return [
    'POST', `/me/shows/${showId}/links`, addLinkRequest
    ] as const;
    }


export const getAddLinkQueryOptions = <TData = Awaited<ReturnType<typeof addLink>>, TError = ErrorResponse>(showId: number,
    addLinkRequest: AddLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAddLinkQueryKey(showId,addLinkRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof addLink>>> = ({ signal }) => addLink(showId,addLinkRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof addLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddLinkQueryResult = NonNullable<Awaited<ReturnType<typeof addLink>>>
export type AddLinkQueryError = ErrorResponse


export function useAddLink<TData = Awaited<ReturnType<typeof addLink>>, TError = ErrorResponse>(
 showId: number,
    addLinkRequest: AddLinkRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof addLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof addLink>>,
          TError,
          Awaited<ReturnType<typeof addLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddLink<TData = Awaited<ReturnType<typeof addLink>>, TError = ErrorResponse>(
 showId: number,
    addLinkRequest: AddLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof addLink>>,
          TError,
          Awaited<ReturnType<typeof addLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddLink<TData = Awaited<ReturnType<typeof addLink>>, TError = ErrorResponse>(
 showId: number,
    addLinkRequest: AddLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Add a reference link
 */

export function useAddLink<TData = Awaited<ReturnType<typeof addLink>>, TError = ErrorResponse>(
 showId: number,
    addLinkRequest: AddLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAddLinkQueryOptions(showId,addLinkRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Update a reference link value (URL or plain text)
 */
export const updateLink = (
    showId: number,
    linkId: number,
    updateLinkRequest: UpdateLinkRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/shows/${showId}/links/${linkId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateLinkRequest, signal
    },
      options);
    }




export const getUpdateLinkQueryKey = (showId: number,
    linkId: number,
    updateLinkRequest?: UpdateLinkRequest,) => {
    return [
    'PATCH', `/me/shows/${showId}/links/${linkId}`, updateLinkRequest
    ] as const;
    }


export const getUpdateLinkQueryOptions = <TData = Awaited<ReturnType<typeof updateLink>>, TError = ErrorResponse>(showId: number,
    linkId: number,
    updateLinkRequest: UpdateLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateLinkQueryKey(showId,linkId,updateLinkRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateLink>>> = ({ signal }) => updateLink(showId,linkId,updateLinkRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined && linkId !== null && linkId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateLinkQueryResult = NonNullable<Awaited<ReturnType<typeof updateLink>>>
export type UpdateLinkQueryError = ErrorResponse


export function useUpdateLink<TData = Awaited<ReturnType<typeof updateLink>>, TError = ErrorResponse>(
 showId: number,
    linkId: number,
    updateLinkRequest: UpdateLinkRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateLink>>,
          TError,
          Awaited<ReturnType<typeof updateLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateLink<TData = Awaited<ReturnType<typeof updateLink>>, TError = ErrorResponse>(
 showId: number,
    linkId: number,
    updateLinkRequest: UpdateLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateLink>>,
          TError,
          Awaited<ReturnType<typeof updateLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateLink<TData = Awaited<ReturnType<typeof updateLink>>, TError = ErrorResponse>(
 showId: number,
    linkId: number,
    updateLinkRequest: UpdateLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update a reference link value (URL or plain text)
 */

export function useUpdateLink<TData = Awaited<ReturnType<typeof updateLink>>, TError = ErrorResponse>(
 showId: number,
    linkId: number,
    updateLinkRequest: UpdateLinkRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateLinkQueryOptions(showId,linkId,updateLinkRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Delete a reference link
 */
export const deleteLink = (
    showId: number,
    linkId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/shows/${showId}/links/${linkId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteLinkQueryKey = (showId: number,
    linkId: number,) => {
    return [
    'DELETE', `/me/shows/${showId}/links/${linkId}`
    ] as const;
    }


export const getDeleteLinkQueryOptions = <TData = Awaited<ReturnType<typeof deleteLink>>, TError = unknown>(showId: number,
    linkId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteLinkQueryKey(showId,linkId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteLink>>> = ({ signal }) => deleteLink(showId,linkId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: showId !== null && showId !== undefined && linkId !== null && linkId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteLinkQueryResult = NonNullable<Awaited<ReturnType<typeof deleteLink>>>
export type DeleteLinkQueryError = unknown


export function useDeleteLink<TData = Awaited<ReturnType<typeof deleteLink>>, TError = unknown>(
 showId: number,
    linkId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteLink>>,
          TError,
          Awaited<ReturnType<typeof deleteLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteLink<TData = Awaited<ReturnType<typeof deleteLink>>, TError = unknown>(
 showId: number,
    linkId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteLink>>,
          TError,
          Awaited<ReturnType<typeof deleteLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteLink<TData = Awaited<ReturnType<typeof deleteLink>>, TError = unknown>(
 showId: number,
    linkId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete a reference link
 */

export function useDeleteLink<TData = Awaited<ReturnType<typeof deleteLink>>, TError = unknown>(
 showId: number,
    linkId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteLinkQueryOptions(showId,linkId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Derived from the user's tracked shows over the local catalog; cached per user with a TTL.
 * @summary Taste profile and catalog recommendations for the home dashboard
 */
export const getRecommendations = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<HomeRecommendations>(
      {url: `/me/recommendations`, method: 'GET', signal
    },
      options);
    }




export const getGetRecommendationsQueryKey = () => {
    return [
    `/me/recommendations`
    ] as const;
    }


export const getGetRecommendationsQueryOptions = <TData = Awaited<ReturnType<typeof getRecommendations>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecommendationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecommendations>>> = ({ signal }) => getRecommendations(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecommendationsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecommendations>>>
export type GetRecommendationsQueryError = ErrorResponse


export function useGetRecommendations<TData = Awaited<ReturnType<typeof getRecommendations>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getRecommendations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecommendations<TData = Awaited<ReturnType<typeof getRecommendations>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getRecommendations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecommendations<TData = Awaited<ReturnType<typeof getRecommendations>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Taste profile and catalog recommendations for the home dashboard
 */

export function useGetRecommendations<TData = Awaited<ReturnType<typeof getRecommendations>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecommendationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get user settings
 */
export const getSettings = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Settings>(
      {url: `/me/settings`, method: 'GET', signal
    },
      options);
    }




export const getGetSettingsQueryKey = () => {
    return [
    `/me/settings`
    ] as const;
    }


export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = unknown


export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user settings
 */

export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Update user settings
 */
export const updateSettings = (
    updateSettingsRequest: UpdateSettingsRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Settings>(
      {url: `/me/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSettingsRequest, signal
    },
      options);
    }




export const getUpdateSettingsQueryKey = (updateSettingsRequest?: UpdateSettingsRequest,) => {
    return [
    'PATCH', `/me/settings`, updateSettingsRequest
    ] as const;
    }


export const getUpdateSettingsQueryOptions = <TData = Awaited<ReturnType<typeof updateSettings>>, TError = unknown>(updateSettingsRequest: UpdateSettingsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateSettingsQueryKey(updateSettingsRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateSettings>>> = ({ signal }) => updateSettings(updateSettingsRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof updateSettings>>>
export type UpdateSettingsQueryError = unknown


export function useUpdateSettings<TData = Awaited<ReturnType<typeof updateSettings>>, TError = unknown>(
 updateSettingsRequest: UpdateSettingsRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateSettings>>,
          TError,
          Awaited<ReturnType<typeof updateSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateSettings<TData = Awaited<ReturnType<typeof updateSettings>>, TError = unknown>(
 updateSettingsRequest: UpdateSettingsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateSettings>>,
          TError,
          Awaited<ReturnType<typeof updateSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateSettings<TData = Awaited<ReturnType<typeof updateSettings>>, TError = unknown>(
 updateSettingsRequest: UpdateSettingsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update user settings
 */

export function useUpdateSettings<TData = Awaited<ReturnType<typeof updateSettings>>, TError = unknown>(
 updateSettingsRequest: UpdateSettingsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateSettingsQueryOptions(updateSettingsRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
