/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Catalog API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  ImportRequest,
  ListShowsParams,
  SearchResults,
  SearchShowsParams,
  Show,
  ShowList
} from './model';

import { customInstance } from '../http';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Search TMDB for shows to add
 */
export const searchShows = (
    params: SearchShowsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SearchResults>(
      {url: `/shows/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getSearchShowsQueryKey = (params?: SearchShowsParams,) => {
    return [
    `/shows/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchShowsQueryOptions = <TData = Awaited<ReturnType<typeof searchShows>>, TError = ErrorResponse>(params: SearchShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchShows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchShowsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchShows>>> = ({ signal }) => searchShows(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchShows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchShowsQueryResult = NonNullable<Awaited<ReturnType<typeof searchShows>>>
export type SearchShowsQueryError = ErrorResponse


export function useSearchShows<TData = Awaited<ReturnType<typeof searchShows>>, TError = ErrorResponse>(
 params: SearchShowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchShows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchShows>>,
          TError,
          Awaited<ReturnType<typeof searchShows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchShows<TData = Awaited<ReturnType<typeof searchShows>>, TError = ErrorResponse>(
 params: SearchShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchShows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchShows>>,
          TError,
          Awaited<ReturnType<typeof searchShows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchShows<TData = Awaited<ReturnType<typeof searchShows>>, TError = ErrorResponse>(
 params: SearchShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchShows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search TMDB for shows to add
 */

export function useSearchShows<TData = Awaited<ReturnType<typeof searchShows>>, TError = ErrorResponse>(
 params: SearchShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchShows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchShowsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Import a show from TMDB into the local catalog
 */
export const importShow = (
    importRequest: ImportRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Show>(
      {url: `/shows/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importRequest, signal
    },
      options);
    }




export const getImportShowQueryKey = (importRequest?: ImportRequest,) => {
    return [
    'POST', `/shows/import`, importRequest
    ] as const;
    }


export const getImportShowQueryOptions = <TData = Awaited<ReturnType<typeof importShow>>, TError = ErrorResponse>(importRequest: ImportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getImportShowQueryKey(importRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof importShow>>> = ({ signal }) => importShow(importRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof importShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ImportShowQueryResult = NonNullable<Awaited<ReturnType<typeof importShow>>>
export type ImportShowQueryError = ErrorResponse


export function useImportShow<TData = Awaited<ReturnType<typeof importShow>>, TError = ErrorResponse>(
 importRequest: ImportRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof importShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof importShow>>,
          TError,
          Awaited<ReturnType<typeof importShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useImportShow<TData = Awaited<ReturnType<typeof importShow>>, TError = ErrorResponse>(
 importRequest: ImportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof importShow>>,
          TError,
          Awaited<ReturnType<typeof importShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useImportShow<TData = Awaited<ReturnType<typeof importShow>>, TError = ErrorResponse>(
 importRequest: ImportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Import a show from TMDB into the local catalog
 */

export function useImportShow<TData = Awaited<ReturnType<typeof importShow>>, TError = ErrorResponse>(
 importRequest: ImportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getImportShowQueryOptions(importRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary List/search the local catalog
 */
export const listShows = (
    params?: ListShowsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ShowList>(
      {url: `/shows`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListShowsQueryKey = (params?: ListShowsParams,) => {
    return [
    `/shows`, ...(params ? [params] : [])
    ] as const;
    }


export const getListShowsQueryOptions = <TData = Awaited<ReturnType<typeof listShows>>, TError = ErrorResponse>(params?: ListShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListShowsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShows>>> = ({ signal }) => listShows(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListShowsQueryResult = NonNullable<Awaited<ReturnType<typeof listShows>>>
export type ListShowsQueryError = ErrorResponse


export function useListShows<TData = Awaited<ReturnType<typeof listShows>>, TError = ErrorResponse>(
 params: undefined |  ListShowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShows>>,
          TError,
          Awaited<ReturnType<typeof listShows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShows<TData = Awaited<ReturnType<typeof listShows>>, TError = ErrorResponse>(
 params?: ListShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShows>>,
          TError,
          Awaited<ReturnType<typeof listShows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListShows<TData = Awaited<ReturnType<typeof listShows>>, TError = ErrorResponse>(
 params?: ListShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List/search the local catalog
 */

export function useListShows<TData = Awaited<ReturnType<typeof listShows>>, TError = ErrorResponse>(
 params?: ListShowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListShowsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Local show detail
 */
export const getShow = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Show>(
      {url: `/shows/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetShowQueryKey = (id: number,) => {
    return [
    `/shows/${id}`
    ] as const;
    }


export const getGetShowQueryOptions = <TData = Awaited<ReturnType<typeof getShow>>, TError = ErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShowQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShow>>> = ({ signal }) => getShow(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShowQueryResult = NonNullable<Awaited<ReturnType<typeof getShow>>>
export type GetShowQueryError = ErrorResponse


export function useGetShow<TData = Awaited<ReturnType<typeof getShow>>, TError = ErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShow>>,
          TError,
          Awaited<ReturnType<typeof getShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShow<TData = Awaited<ReturnType<typeof getShow>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShow>>,
          TError,
          Awaited<ReturnType<typeof getShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShow<TData = Awaited<ReturnType<typeof getShow>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Local show detail
 */

export function useGetShow<TData = Awaited<ReturnType<typeof getShow>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShowQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
