// Package authapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package authapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Tokens TokenPair `json:"tokens"`
	User   User      `json:"user"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// OAuthExchangeRequest defines model for OAuthExchangeRequest.
type OAuthExchangeRequest struct {
	Code string `json:"code"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// User defines model for User.
type User struct {
	DisplayName string   `json:"display_name"`
	Email       *string  `json:"email,omitempty"`
	Id          int64    `json:"id"`
	Role        UserRole `json:"role"`
	Timezone    string   `json:"timezone"`
}

// UserRole defines model for User.Role.
type UserRole string

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// OauthExchangeJSONRequestBody defines body for OauthExchange for application/json ContentType.
type OauthExchangeJSONRequestBody = OAuthExchangeRequest

// PasswordChangeJSONRequestBody defines body for PasswordChange for application/json ContentType.
type PasswordChangeJSONRequestBody = ChangePasswordRequest

// PasswordForgotJSONRequestBody defines body for PasswordForgot for application/json ContentType.
type PasswordForgotJSONRequestBody = ForgotPasswordRequest

// PasswordResetJSONRequestBody defines body for PasswordReset for application/json ContentType.
type PasswordResetJSONRequestBody = ResetPasswordRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Log in with email and password
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Logout Revoke the refresh token family
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// GetMe Current authenticated user
	// (GET /auth/me)
	GetMe(ctx echo.Context) error
	// OauthExchange Exchange a handoff code for tokens
	// (POST /auth/oauth/exchange)
	OauthExchange(ctx echo.Context) error
	// OauthRedirect Redirect to a social provider's consent screen
	// (GET /auth/oauth/{provider})
	OauthRedirect(ctx echo.Context, provider string) error
	// OauthCallback OAuth provider callback (redirects to the SPA with a handoff code)
	// (GET /auth/oauth/{provider}/callback)
	OauthCallback(ctx echo.Context, provider string, params OauthCallbackParams) error
	// PasswordChange Change the current user's password
	// (POST /auth/password/change)
	PasswordChange(ctx echo.Context) error
	// PasswordForgot Request a password-reset email
	// (POST /auth/password/forgot)
	PasswordForgot(ctx echo.Context) error
	// PasswordReset Set a new password using a reset token
	// (POST /auth/password/reset)
	PasswordReset(ctx echo.Context) error
	// Refresh Rotate a refresh token
	// (POST /auth/refresh)
	Refresh(ctx echo.Context) error
	// Register Register a password account
	// (POST /auth/register)
	Register(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// OauthExchange converts echo context to params.
func (w *ServerInterfaceWrapper) OauthExchange(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OauthExchange(ctx)
	return err
}

// OauthRedirect converts echo context to params.
func (w *ServerInterfaceWrapper) OauthRedirect(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OauthRedirect(ctx, provider)
	return err
}

// OauthCallback converts echo context to params.
func (w *ServerInterfaceWrapper) OauthCallback(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OauthCallbackParams
	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", ctx.QueryParams(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OauthCallback(ctx, provider, params)
	return err
}

// PasswordChange converts echo context to params.
func (w *ServerInterfaceWrapper) PasswordChange(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PasswordChange(ctx)
	return err
}

// PasswordForgot converts echo context to params.
func (w *ServerInterfaceWrapper) PasswordForgot(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PasswordForgot(ctx)
	return err
}

// PasswordReset converts echo context to params.
func (w *ServerInterfaceWrapper) PasswordReset(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PasswordReset(ctx)
	return err
}

// Refresh converts echo context to params.
func (w *ServerInterfaceWrapper) Refresh(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Refresh(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/register", wrapper.Register, options.OperationMiddlewares["register"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh, options.OperationMiddlewares["refresh"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.POST(options.BaseURL+"/auth/password/forgot", wrapper.PasswordForgot, options.OperationMiddlewares["passwordForgot"]...)
	router.POST(options.BaseURL+"/auth/password/reset", wrapper.PasswordReset, options.OperationMiddlewares["passwordReset"]...)
	router.POST(options.BaseURL+"/auth/password/change", wrapper.PasswordChange, options.OperationMiddlewares["passwordChange"]...)
	router.GET(options.BaseURL+"/auth/oauth/:provider", wrapper.OauthRedirect, options.OperationMiddlewares["oauthRedirect"]...)
	router.GET(options.BaseURL+"/auth/oauth/:provider/callback", wrapper.OauthCallback, options.OperationMiddlewares["oauthCallback"]...)
	router.POST(options.BaseURL+"/auth/oauth/exchange", wrapper.OauthExchange, options.OperationMiddlewares["oauthExchange"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FhRb9s2EP4rBDegG6DFThMUmN4yox26dUvgtNhDEASMdJLYSKRCUsm8wP99OJKSJVu2bM/OBuwlUKzT",
	"3fH7jt8d+UIjWZRSgDCahi9UgS6l0GD/ea+UVPgQSWFAGHxkZZnziBkuxeirlgJ/01EGBcOnbxUkNKTf",
	"jBZeR+6tHjlv8/k8oDHoSPESndCQ1i8C78jGvqhMNvXJ4P+lkiUow11mRj6A0EMRP6PVFeOKzgNaaVBD",
	"H3xBG0xEwWPFFcQ0vHEfBnXI24CaWQk0pPL+K0QGXU8yJlK4Ylo/SxVP4bECbVaTjiqlQJi70hvahThf",
	"2iguUvQl4LljUHDxCURqMhq+C5bNlzJdCbDkri/3huNurgVozVLoSXEpZm3Y5/uDVKk0g7hAwXiOD4lU",
	"BTM09L8MLddZ9QX+JFMu/nm8gG6gqjeZ1hdr8pKVWZuYgkSBzu5sqQ2H7Jr3xbvEXfT+z8jW5/q6lPEW",
	"RFurviBTl8brrWoKKdcG1KEJ3mWrbUX3FDQMl/9OO97r0DCMzmwLAViI5EpmLIpA67XEBbtS2/EXbMH0",
	"F6/Z3bRirsucze4EK6A3rYZ/UeU5u8+BhkZV0AMmjztlwoV5d74oEy4MpGC7h5K5jQWiKlpNgcUFb6fe",
	"ookX8JcUW2wsjjrdWZMP13KyCg52S4gqxc3sGruXg+YemAKFu37x34d6db/88Zn6Houe3NvFajNjStee",
	"uUikzZsbXDWNIbnO5LMm6JhcXH2kAX0CpV37Hp+cnoxxybIEwUpOQ3p2Mj45s7vDZDavEatMNspRli2f",
	"0m0EZNWOEh9jGjrVpg4c0OYnGc8ONnx0OsK8SwHWhv2hNfq8HY8PFrszyvTMP5e/InrnLmKfoyazeoZC",
	"69OtrbFUqqJgauZAJlyQZ24yYvcJYSImjUKgcUOWrMxGtvD90ehqNcqt+Dq30tAB9ndJJj6bLghTeJIP",
	"QEwGxIsQsSJEElbwfNZCwSlMCj0A/AzmN7tXj1U3fhpdWy+7VYAXCxredGXi5nZ+28Zm4oZIgssHYTB1",
	"iElVT8YOFmn/gp8s1hfJJWsNIEeqld4h5z+6xffctPXqCCMZE7FMEoLjGEmkIv5csszNS6nkE49BzdcW",
	"sCVnCjFX2FFQrRUrwIDStkhQqq2C4xRhWy2tfdJlbIMWTsvd7nYJ97Px29Wt2qRhYTrfD6baCTGSMKJl",
	"xFlO6pzfaBLhp8IQHSkAsQGyUcTy/J5FD5uxm9RWR8Mu8K4eK1CzhS87i+/xnTbMbP5wR7I68NuN2OBN",
	"agzJd8rbayQGRff66sJ1oG49f9+ipO5IoyGJqefryTE1pv+E/z+cI7buIk6vkGx/K2FbyBvdN2o0XCf2",
	"wmCYa3excCSu+28tDjGD7EbOkrTZNAhr8PtB4enSzXB9WNrXw1DaM+qRkOw9//7LQF4DgijguQGSVJqL",
	"lDDiAHWn0QWgfkBcj6S//zgahp3blVeWnNYN6sGHmqnEbmRxb43gHeTdPc8m6L3FsbDvXjRtBf7pq+n9",
	"RAHO5vuI/o/7qpADpCVDhEWRrOwJaz7/OwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
