// Package usersapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package usersapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ShowRefAiringStatus.
const (
	Airing         ShowRefAiringStatus = "airing"
	BetweenSeasons ShowRefAiringStatus = "between_seasons"
	Ended          ShowRefAiringStatus = "ended"
	NotStarted     ShowRefAiringStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ShowRefAiringStatus enum.
func (e ShowRefAiringStatus) Valid() bool {
	switch e {
	case Airing:
		return true
	case BetweenSeasons:
		return true
	case Ended:
		return true
	case NotStarted:
		return true
	default:
		return false
	}
}

// Defines values for UserShowStatus.
const (
	Completed   UserShowStatus = "completed"
	Dropped     UserShowStatus = "dropped"
	OnHold      UserShowStatus = "on_hold"
	PlanToWatch UserShowStatus = "plan_to_watch"
	Watching    UserShowStatus = "watching"
)

// Valid indicates whether the value is a known member of the UserShowStatus enum.
func (e UserShowStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Dropped:
		return true
	case OnHold:
		return true
	case PlanToWatch:
		return true
	case Watching:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Progress defines model for Progress.
type Progress struct {
	NextUnwatchedEpisodeId *int64 `json:"next_unwatched_episode_id,omitempty"`

	// Total Episodes with a known air date of today or earlier
	Total int `json:"total"`

	// Watched Watched episodes that have already aired
	Watched int `json:"watched"`
}

// ShowRef defines model for ShowRef.
type ShowRef struct {
	AiringStatus       ShowRefAiringStatus `json:"airing_status"`
	Id                 int64               `json:"id"`
	NextEpisodeAirDate *string             `json:"next_episode_air_date,omitempty"`
	OriginalTitle      *string             `json:"original_title,omitempty"`
	PosterUrl          *string             `json:"poster_url,omitempty"`

	// SeasonCount Catalog seasons excluding specials
	SeasonCount *int     `json:"season_count,omitempty"`
	Title       string   `json:"title"`
	TmdbId      int64    `json:"tmdb_id"`
	VoteAverage *float32 `json:"vote_average,omitempty"`
	VoteCount   *int64   `json:"vote_count,omitempty"`
}

// ShowRefAiringStatus defines model for ShowRef.AiringStatus.
type ShowRefAiringStatus string

// TrackedShow defines model for TrackedShow.
type TrackedShow struct {
	Progress Progress `json:"progress"`
	Show     ShowRef  `json:"show"`
	UserShow UserShow `json:"user_show"`
}

// TrackedShowList defines model for TrackedShowList.
type TrackedShowList struct {
	Tracked []TrackedShow `json:"tracked"`
}

// UserList defines model for UserList.
type UserList struct {
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
	Total    int64         `json:"total"`
	Users    []UserSummary `json:"users"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	DisplayName string `json:"display_name"`
	Id          int64  `json:"id"`
	IsPublic    bool   `json:"is_public"`
	ShowsCount  int    `json:"shows_count"`
}

// UserShow defines model for UserShow.
type UserShow struct {
	Favorite         bool           `json:"favorite"`
	Id               int64          `json:"id"`
	PreferredDubbing *string        `json:"preferred_dubbing,omitempty"`
	ShowId           int64          `json:"show_id"`
	Status           UserShowStatus `json:"status"`
}

// UserShowStatus defines model for UserShow.Status.
type UserShowStatus string

// UserSummary defines model for UserSummary.
type UserSummary struct {
	DisplayName string  `json:"display_name"`
	Email       *string `json:"email,omitempty"`
	Id          int64   `json:"id"`
	IsPublic    bool    `json:"is_public"`
	ShowsCount  int     `json:"shows_count"`
}

// UserId defines model for UserId.
type UserId = int64

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Q        *string `form:"q,omitempty" json:"q,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListUsers Search the public user directory with pagination
	// (GET /users)
	ListUsers(ctx echo.Context, params ListUsersParams) error
	// GetUserProfile One user's public profile metadata
	// (GET /users/{userId})
	GetUserProfile(ctx echo.Context, userId UserId) error
	// ListUserShows A user's tracked shows (only if the profile is public, or it's you/an admin)
	// (GET /users/{userId}/shows)
	ListUserShows(ctx echo.Context, userId UserId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListUsers converts echo context to params.
func (w *ServerInterfaceWrapper) ListUsers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUsers(ctx, params)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx, userId)
	return err
}

// ListUserShows converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserShows(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserShows(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/users", wrapper.ListUsers, options.OperationMiddlewares["listUsers"]...)
	router.GET(options.BaseURL+"/users/:userId", wrapper.GetUserProfile, options.OperationMiddlewares["getUserProfile"]...)
	router.GET(options.BaseURL+"/users/:userId/shows", wrapper.ListUserShows, options.OperationMiddlewares["listUserShows"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FdRj9s2DP4rgjagG2BckrbYQ96KYRu6FWixtuhDcTAYi4nV2pJK0XfNDvnvgyQ7dhLlLt26YVieHEsm",
	"P/L7RFJ3srKtswYNe7m8kw4IWmSk+O+tR3quwpM2cikdcC0LaaBFuZRdWiwk4adOEyq5ZOqwkL6qsYXw",
	"1dpSCyyXUhv+4aksJG8dpr+4QZK73S587p01HqPHn4gshYfKGkbD4RGca3QFrK2ZffDWhHejj28J13Ip",
	"v5mNgczSqp8la9GLQl+RdsGIXMphYQB76NuRdUisE6QWvYcNhscevmfSZiMT+CH29/uN1/s47eoDVix3",
	"hXxFdkPo/al5g5+57MwtcFWjKtFpbxWWWmUTaLqmgVWDQ66PE1pItgxN+PYo4mTXi1vNtQDx0dhbI0CT",
	"UMAo7FqwVbAVlgQCNRpJ5qz3ME/tv0sLAgc/XAOLGm5QQEMIahucocqJ4DCNg4shlFw6X9f29vfA+3E2",
	"QQdqSs/AXXyBpmuDVWM5vCWOltM2WcgV8i2iKT2Ct8bLQqJRqCZOB7ILeYaS0yRFSgciQVMZUhy5zrM3",
	"urCkN9pAU7LmJie5QjrrGansqMkup0DKynbp8Byy9CMwNHYj+nAFfq6aTmmzEd5hpaEJGWi10W3I2jyr",
	"r7PIuFWr8uIk3VjGEm6QDs+W6drVZMM+jodLyaGKdBRQj2hAXRzpIyetNwTVR1RBYafycpNjfF/h2R/3",
	"wEhv6b79g553RSyr5SXfhOIcUR6HPlronRcj7gcifqE9n0bNaUPsA4ztg9FPU7jbOwQi2J6AHWzngIUI",
	"84jcoWgmsgorpdd/nFneV8cLFBry6C8OOtLRtS3Q9sGgk+UBTQItp9jPZeMV2bVOx+8wIUp718C2TL35",
	"7m8UL+1L160aXU3MrKxtEMygZj8ey0tO4QG2qYNDa+dizp/ENdxY0ox5lBdH6wjXSISqVN1qFXKVLaq1",
	"vb28sp02n9jSUsNxDZiSbRlfyUJaU9a2CWkKmmow9SdF1rlsG8oleIC3d12M6Tmb1V6qX64kbEE3/xuN",
	"xZZZdaR5+zqc5JSEFQIhPeu4Hv/9PMT167s3sh8cI/C4OsZZM7s0c2qztjGA1DKlwnUQsxeBAC+evXou",
	"C3mD5FNznl8truZxCnBowGm5lE+u5ldPYmXgOgKb7YvSBmNyAnVxNA5zugzV8m1fXKaj/Pt+gv/UIW3H",
	"Ef6TnE7rLXx+gWYTYl7M5xnl5Y30xWu0o3ANXcNyuSiCzTRLLObxN5kuFrkeft5FKoxZP4/nh44ecHJ9",
	"dOd4PJ9/tRvHvmVlLh0vfwvkPk3eckb2qIaLS9i9uHh3kPJwquVrBKpqwTWKdBJEUI5QmrBiS9t0D3AQ",
	"xs2IL3ye1DW7S1e73VmZ/YI87UYnWsvBHbfM+mvlP07EgO8eLhZfxMXTv8bFS4Mx+4/8wIVLyESLDAoY",
	"ctmfxcL14FGPFeU/ScHxXPnVaHjyb5D2bKCsn1BFpEN8Z02zFXqdTlZPox6ILcL9WfMjL7a2m4ERoFpt",
	"vk+hD30m8jPtMO+vd9e7PwMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
