/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Social API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedCardType } from './feedCardType';
import type { FeedEpisode } from './feedEpisode';
import type { FeedShow } from './feedShow';
import type { FollowUser } from './followUser';

export interface FeedCard {
  actor?: FollowUser;
  type: FeedCardType;
  show: FeedShow;
  season_number?: number;
  /** Episodes grouped into a watched_episode card, newest first */
  episodes?: FeedEpisode[];
  /** Number of episodes in a watched_episode group */
  count: number;
  rating?: number;
  created_at: string;
}
