/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Social API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedCard } from './feedCard';

export interface FeedPage {
  cards: FeedCard[];
  next_cursor?: string;
}
