/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Social API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Resulting follow state
 */
export type FollowResultStatus = typeof FollowResultStatus[keyof typeof FollowResultStatus];


export const FollowResultStatus = {
  pending: 'pending',
  accepted: 'accepted',
} as const;
