/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Social API
 * OpenAPI spec version: 0.1.0
 */
import type { FollowResultStatus } from './followResultStatus';

export interface FollowResult {
  /** Resulting follow state */
  status: FollowResultStatus;
}
