/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { ListReportsStatus } from './listReportsStatus';

export type ListReportsParams = {
status?: ListReportsStatus;
/**
 * @minimum 1
 * @maximum 1000000
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
