/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { ResolveReportRequestStatus } from './resolveReportRequestStatus';

export interface ResolveReportRequest {
  status: ResolveReportRequestStatus;
}
