/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Admin API
 * OpenAPI spec version: 0.1.0
 */

export type ResolveReportRequestStatus = typeof ResolveReportRequestStatus[keyof typeof ResolveReportRequestStatus];


export const ResolveReportRequestStatus = {
  resolved: 'resolved',
  dismissed: 'dismissed',
} as const;
