// Package socialapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package socialapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for FeedCardType.
const (
	AddedShow      FeedCardType = "added_show"
	FinishedSeason FeedCardType = "finished_season"
	FinishedShow   FeedCardType = "finished_show"
	RatedShow      FeedCardType = "rated_show"
	WatchedEpisode FeedCardType = "watched_episode"
)

// Valid indicates whether the value is a known member of the FeedCardType enum.
func (e FeedCardType) Valid() bool {
	switch e {
	case AddedShow:
		return true
	case FinishedSeason:
		return true
	case FinishedShow:
		return true
	case RatedShow:
		return true
	case WatchedEpisode:
		return true
	default:
		return false
	}
}

// Defines values for FollowResultStatus.
const (
	Accepted FollowResultStatus = "accepted"
	Pending  FollowResultStatus = "pending"
)

// Valid indicates whether the value is a known member of the FollowResultStatus enum.
func (e FollowResultStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// FeedCard defines model for FeedCard.
type FeedCard struct {
	Actor *FollowUser `json:"actor,omitempty"`

	// Count Number of episodes in a watched_episode group
	Count     int       `json:"count"`
	CreatedAt time.Time `json:"created_at"`

	// Episodes Episodes grouped into a watched_episode card, newest first
	Episodes     *[]FeedEpisode `json:"episodes,omitempty"`
	Rating       *int           `json:"rating,omitempty"`
	SeasonNumber *int           `json:"season_number,omitempty"`
	Show         FeedShow       `json:"show"`
	Type         FeedCardType   `json:"type"`
}

// FeedCardType defines model for FeedCard.Type.
type FeedCardType string

// FeedEpisode defines model for FeedEpisode.
type FeedEpisode struct {
	EpisodeNumber int `json:"episode_number"`
	SeasonNumber  int `json:"season_number"`
}

// FeedPage defines model for FeedPage.
type FeedPage struct {
	Cards      []FeedCard `json:"cards"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// FeedShow defines model for FeedShow.
type FeedShow struct {
	Id        int64   `json:"id"`
	PosterUrl *string `json:"poster_url,omitempty"`
	Title     string  `json:"title"`
	TmdbId    int64   `json:"tmdb_id"`
}

// FollowResult defines model for FollowResult.
type FollowResult struct {
	// Status Resulting follow state
	Status FollowResultStatus `json:"status"`
}

// FollowResultStatus Resulting follow state
type FollowResultStatus string

// FollowUser defines model for FollowUser.
type FollowUser struct {
	DisplayName string `json:"display_name"`
	Id          int64  `json:"id"`
	IsPublic    bool   `json:"is_public"`
}

// FollowUserList defines model for FollowUserList.
type FollowUserList struct {
	Total int64        `json:"total"`
	Users []FollowUser `json:"users"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// UserId defines model for UserId.
type UserId = int64

// GetHomeFeedParams defines parameters for GetHomeFeed.
type GetHomeFeedParams struct {
	// Cursor Opaque keyset cursor from a previous page's next_cursor
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetProfileFeedParams defines parameters for GetProfileFeed.
type GetProfileFeedParams struct {
	// Cursor Opaque keyset cursor from a previous page's next_cursor
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListFollowersParams defines parameters for ListFollowers.
type ListFollowersParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListFollowingParams defines parameters for ListFollowing.
type ListFollowingParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHomeFeed Aggregated activity of everyone the current user follows (accepted)
	// (GET /me/feed)
	GetHomeFeed(ctx echo.Context, params GetHomeFeedParams) error
	// ListIncomingRequests Pending follow requests addressed to the current user
	// (GET /me/follows/incoming)
	ListIncomingRequests(ctx echo.Context) error
	// ApproveFollower Approve a pending follow request
	// (POST /me/follows/incoming/{userId}/approve)
	ApproveFollower(ctx echo.Context, userId UserId) error
	// RejectFollower Reject (delete) a pending follow request
	// (POST /me/follows/incoming/{userId}/reject)
	RejectFollower(ctx echo.Context, userId UserId) error
	// UnfollowUser Unfollow a user or cancel a pending request. Idempotent.
	// (DELETE /me/follows/{userId})
	UnfollowUser(ctx echo.Context, userId UserId) error
	// FollowUser Follow a user (instant for public, a pending request for private). Idempotent.
	// (POST /me/follows/{userId})
	FollowUser(ctx echo.Context, userId UserId) error
	// GetProfileFeed A user's activity feed (visible per profile privacy)
	// (GET /users/{userId}/feed)
	GetProfileFeed(ctx echo.Context, userId UserId, params GetProfileFeedParams) error
	// ListFollowers A user's accepted followers (visible per profile privacy)
	// (GET /users/{userId}/followers)
	ListFollowers(ctx echo.Context, userId UserId, params ListFollowersParams) error
	// ListFollowing Users this user follows (visible per profile privacy)
	// (GET /users/{userId}/following)
	ListFollowing(ctx echo.Context, userId UserId, params ListFollowingParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHomeFeed converts echo context to params.
func (w *ServerInterfaceWrapper) GetHomeFeed(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHomeFeedParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHomeFeed(ctx, params)
	return err
}

// ListIncomingRequests converts echo context to params.
func (w *ServerInterfaceWrapper) ListIncomingRequests(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListIncomingRequests(ctx)
	return err
}

// ApproveFollower converts echo context to params.
func (w *ServerInterfaceWrapper) ApproveFollower(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApproveFollower(ctx, userId)
	return err
}

// RejectFollower converts echo context to params.
func (w *ServerInterfaceWrapper) RejectFollower(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RejectFollower(ctx, userId)
	return err
}

// UnfollowUser converts echo context to params.
func (w *ServerInterfaceWrapper) UnfollowUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnfollowUser(ctx, userId)
	return err
}

// FollowUser converts echo context to params.
func (w *ServerInterfaceWrapper) FollowUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FollowUser(ctx, userId)
	return err
}

// GetProfileFeed converts echo context to params.
func (w *ServerInterfaceWrapper) GetProfileFeed(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProfileFeedParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProfileFeed(ctx, userId, params)
	return err
}

// ListFollowers converts echo context to params.
func (w *ServerInterfaceWrapper) ListFollowers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowersParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListFollowers(ctx, userId, params)
	return err
}

// ListFollowing converts echo context to params.
func (w *ServerInterfaceWrapper) ListFollowing(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowingParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListFollowing(ctx, userId, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(options.BaseURL+"/me/follows/:userId", wrapper.UnfollowUser, options.OperationMiddlewares["unfollowUser"]...)
	router.POST(options.BaseURL+"/me/follows/:userId", wrapper.FollowUser, options.OperationMiddlewares["followUser"]...)
	router.GET(options.BaseURL+"/me/follows/incoming", wrapper.ListIncomingRequests, options.OperationMiddlewares["listIncomingRequests"]...)
	router.POST(options.BaseURL+"/me/follows/incoming/:userId/approve", wrapper.ApproveFollower, options.OperationMiddlewares["approveFollower"]...)
	router.POST(options.BaseURL+"/me/follows/incoming/:userId/reject", wrapper.RejectFollower, options.OperationMiddlewares["rejectFollower"]...)
	router.GET(options.BaseURL+"/users/:userId/followers", wrapper.ListFollowers, options.OperationMiddlewares["listFollowers"]...)
	router.GET(options.BaseURL+"/users/:userId/following", wrapper.ListFollowing, options.OperationMiddlewares["listFollowing"]...)
	router.GET(options.BaseURL+"/me/feed", wrapper.GetHomeFeed, options.OperationMiddlewares["getHomeFeed"]...)
	router.GET(options.BaseURL+"/users/:userId/feed", wrapper.GetProfileFeed, options.OperationMiddlewares["getProfileFeed"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fhvb9u2E/4qBH8/oAmgxU6b7YXfBUW9ZSvWoFmxF0Fg0OLJZieRDHly6gX+7sORkiXZ8p8Uafe3r0Lz",
	"yOfuueeOpz7y1BTWaNDo+eiRW+FEAQgurF6XzhtHf0nwqVMWldF8xN9ZcV8C+w2WHpClwYplzhRMMOtg",
	"oUzpmRUzeOGZhk84iSY84YqO35fgljzhWhTAR3y96dM5FILgcGlpx6NTesZXq4S/VYVC2uq7IQ+b7Qsk",
	"ZKLMkY9eDhNeiE+qKAs++pYWSsfFeVLDKI0wAxdwrsUMdsFQRP0o5y2Q82H4dxTSjfp9L9rEk8HhwM6P",
	"wPvgwV3JNZoVOG/AyriZcAf3pXIg+QhdCW3kzLhCYLz0uwveg7Gi494a7SHI541zUT2p0Qg6pE9Ym6tU",
	"kJAGHz2p6bGF8X8HGR/x/w0aVQ7irh/E2wJKV431Ru1sF9s6Y8Ghii4V4H2V4W2NNbHfrg3v1nGa6UdI",
	"ka8SPgaQr4WT29eLFCPqvkDGJs/NA6WDLktNGZnpBvVzWUzBMZMxsMobCZ4pzQR7EJjOQU6qX9nMmdL2",
	"JCPhqQOBICcCO9mTAuEbVAU0h2oKEl5jbfvzpvYiAIJkSqPp8ScVTiZMwwN4ZJlynupSIRT+IC0AskIh",
	"VyrfhHNiSWsnkJxsEtcK1YPwRk904GyHydw8HOPBDdmt4R85aKqoW74RJ094prTy9FNE7/xClyRcSNks",
	"XEhGWNwlB8QXdiufa4V0ErpLlTV/W8Ks3N5P0SEWN7zs2iebGLt8rDts10HSTfjjaK2ECuwRSvvBOVjm",
	"EXaXqzeVaLquKnlUO0y4NR7BTUqX9ziScFSYQ/9OIaeTI2E2AlLUxOvzNUZvfKELvQcfXpPNGD0KLHva",
	"QLRXesaycJ6RIWm1rhMLWlIUCRdpChZBHpZ7Bbbby9Art3yUyttcLCfxCeuh8ehEKT+x5TRXaeuaqTE5",
	"CN1PcAe6fX5/DG+V7+EaDYr8SE/pnX5CmXRemm6hbIQVL04qZ7bDCP0hLZ3C5Q3dHl2fgnDgLkucN6tx",
	"HcWPv/5Sjy6B0LDbRDVHtPE5VzozgYhYEDTjUOV5dmNSJXJ2eX3FE74A56MIh2fnZ0OKyFjQwio+4q/O",
	"hmeveBKmmuDZoIBBBhAUMIPAOnEeBg+agvj3gD+YAqjMw7lm7r3tJ7UxGVRz8So5aBnH1tXdxmT0cjh8",
	"trlo3VN7RqN3PxFNF8PzXZesvRq0pqiyKIRb8hG/nM0czOjRYSJFtVC4DBPJAtzSaGA4B5r+HWhkJKCq",
	"KXh2Uhf/abgxJCNuDZROTVG95L2JoSK5qozew30JHj3/kvx1y/P5WbyOLbHumK6KiQkpHXgPkqHZonIn",
	"b4PHOKuvBsJaZxbxLTW+h8nLaBADDKX3NJlXXww96r3oGVgNe12l44lkkfXFZwo0Rkifnb0kH8Gig9Dg",
	"dpL4Puz/gzmMAbITCTkgnB7PZU1hjIMOb7P3QWfNG/QX5a7DRu0wE7GjGcdSoVPIW7xUhJyxKwmFNYR5",
	"Vs972xSMvwQBz93+qjlwT/MbPkmLX0W5406mTpT2KDSyzDgWx7FkO2lx16mFQDjdyCDpO8xBTXc4NEJc",
	"O5Op/POmiDq7yb953iDrV1/lqQgqeeGbSYZyy04WyqtpDswC6SJkM+ojXZ72S6J6CvzeCWa8tvpysohZ",
	"OM4u/E/jV2gkzztH/RnqiIMrW6f5syVyaMgdr63+k8jfQCLktmc4V37jW+eAPFpfziG37W/m27vV3eqP",
	"AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
