/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { Error } from './error';

/**
 * Error
 */
export type ErrorResponse = Error;
