/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */

export type LinkKind = typeof LinkKind[keyof typeof LinkKind];


export const LinkKind = {
  download: 'download',
  streaming: 'streaming',
  wiki: 'wiki',
  imdb: 'imdb',
  kinopoisk: 'kinopoisk',
} as const;
