/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */

export interface Progress {
  watched_episode_ids: number[];
  /** Watched episodes that have already aired */
  watched: number;
  /** Episodes with a known air date of today or earlier */
  total: number;
  /** Aired but not-yet-watched episodes */
  unwatched: number;
  /** @nullable */
  next_unwatched_episode_id?: number | null;
}
