/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { TasteGenre } from './tasteGenre';
import type { TasteLanguage } from './tasteLanguage';

export interface Taste {
  genres: TasteGenre[];
  languages: TasteLanguage[];
}
