/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateShowRequestStatus } from './updateShowRequestStatus';

export interface UpdateShowRequest {
  status?: UpdateShowRequestStatus;
  favorite?: boolean;
  preferred_dubbing?: string;
}
