/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateSettingsRequest {
  timezone: string;
  is_public?: boolean;
}
