/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Tracking API
 * OpenAPI spec version: 0.1.0
 */
import type { UserShowStatus } from './userShowStatus';

export interface UserShow {
  id: number;
  show_id: number;
  status: UserShowStatus;
  favorite: boolean;
  preferred_dubbing?: string;
  /**
     * The user's own 1..10 score; null when unrated
     * @minimum 1
     * @maximum 10
     * @nullable
     */
  rating?: number | null;
}
