/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Notes & Recap API
 * OpenAPI spec version: 0.1.0
 */
import type { Note } from './note';

export interface NoteList {
  notes: Note[];
}
