/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Auth API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  ErrorResponse,
  LoginRequest,
  LogoutRequest,
  OAuthExchangeRequest,
  OauthCallbackParams,
  RefreshRequest,
  RegisterRequest,
  TokenPair,
  User
} from './model';

import { customInstance } from '../http';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Register a password account
 */
export const register = (
    registerRequest: RegisterRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AuthResponse>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      options);
    }




export const getRegisterQueryKey = (registerRequest?: RegisterRequest,) => {
    return [
    'POST', `/auth/register`, registerRequest
    ] as const;
    }


export const getRegisterQueryOptions = <TData = Awaited<ReturnType<typeof register>>, TError = ErrorResponse>(registerRequest: RegisterRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof register>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegisterQueryKey(registerRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof register>>> = ({ signal }) => register(registerRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof register>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegisterQueryResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type RegisterQueryError = ErrorResponse


export function useRegister<TData = Awaited<ReturnType<typeof register>>, TError = ErrorResponse>(
 registerRequest: RegisterRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof register>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof register>>,
          TError,
          Awaited<ReturnType<typeof register>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegister<TData = Awaited<ReturnType<typeof register>>, TError = ErrorResponse>(
 registerRequest: RegisterRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof register>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof register>>,
          TError,
          Awaited<ReturnType<typeof register>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegister<TData = Awaited<ReturnType<typeof register>>, TError = ErrorResponse>(
 registerRequest: RegisterRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof register>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Register a password account
 */

export function useRegister<TData = Awaited<ReturnType<typeof register>>, TError = ErrorResponse>(
 registerRequest: RegisterRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof register>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegisterQueryOptions(registerRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Log in with email and password
 */
export const login = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AuthResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }




export const getLoginQueryKey = (loginRequest?: LoginRequest,) => {
    return [
    'POST', `/auth/login`, loginRequest
    ] as const;
    }


export const getLoginQueryOptions = <TData = Awaited<ReturnType<typeof login>>, TError = ErrorResponse>(loginRequest: LoginRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginQueryKey(loginRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof login>>> = ({ signal }) => login(loginRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginQueryResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginQueryError = ErrorResponse


export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = ErrorResponse>(
 loginRequest: LoginRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = ErrorResponse>(
 loginRequest: LoginRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = ErrorResponse>(
 loginRequest: LoginRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Log in with email and password
 */

export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = ErrorResponse>(
 loginRequest: LoginRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginQueryOptions(loginRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Rotate a refresh token
 */
export const refresh = (
    refreshRequest: RefreshRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TokenPair>(
      {url: `/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }




export const getRefreshQueryKey = (refreshRequest?: RefreshRequest,) => {
    return [
    'POST', `/auth/refresh`, refreshRequest
    ] as const;
    }


export const getRefreshQueryOptions = <TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorResponse>(refreshRequest: RefreshRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRefreshQueryKey(refreshRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof refresh>>> = ({ signal }) => refresh(refreshRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RefreshQueryResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
export type RefreshQueryError = ErrorResponse


export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorResponse>(
 refreshRequest: RefreshRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof refresh>>,
          TError,
          Awaited<ReturnType<typeof refresh>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorResponse>(
 refreshRequest: RefreshRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof refresh>>,
          TError,
          Awaited<ReturnType<typeof refresh>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorResponse>(
 refreshRequest: RefreshRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Rotate a refresh token
 */

export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorResponse>(
 refreshRequest: RefreshRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRefreshQueryOptions(refreshRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Revoke the refresh token family
 */
export const logout = (
    logoutRequest: LogoutRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutRequest, signal
    },
      options);
    }




export const getLogoutQueryKey = (logoutRequest?: LogoutRequest,) => {
    return [
    'POST', `/auth/logout`, logoutRequest
    ] as const;
    }


export const getLogoutQueryOptions = <TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(logoutRequest: LogoutRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutQueryKey(logoutRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof logout>>> = ({ signal }) => logout(logoutRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogoutQueryResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type LogoutQueryError = unknown


export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
 logoutRequest: LogoutRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logout>>,
          TError,
          Awaited<ReturnType<typeof logout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
 logoutRequest: LogoutRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logout>>,
          TError,
          Awaited<ReturnType<typeof logout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
 logoutRequest: LogoutRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Revoke the refresh token family
 */

export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
 logoutRequest: LogoutRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogoutQueryOptions(logoutRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Redirect to a social provider's consent screen
 */
export const oauthRedirect = (
    provider: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/auth/oauth/${provider}`, method: 'GET', signal
    },
      options);
    }




export const getOauthRedirectQueryKey = (provider: string,) => {
    return [
    `/auth/oauth/${provider}`
    ] as const;
    }


export const getOauthRedirectQueryOptions = <TData = Awaited<ReturnType<typeof oauthRedirect>>, TError = void | ErrorResponse>(provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthRedirect>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthRedirectQueryKey(provider);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof oauthRedirect>>> = ({ signal }) => oauthRedirect(provider, requestOptions, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oauthRedirect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthRedirectQueryResult = NonNullable<Awaited<ReturnType<typeof oauthRedirect>>>
export type OauthRedirectQueryError = void | ErrorResponse


export function useOauthRedirect<TData = Awaited<ReturnType<typeof oauthRedirect>>, TError = void | ErrorResponse>(
 provider: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthRedirect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oauthRedirect>>,
          TError,
          Awaited<ReturnType<typeof oauthRedirect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthRedirect<TData = Awaited<ReturnType<typeof oauthRedirect>>, TError = void | ErrorResponse>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthRedirect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oauthRedirect>>,
          TError,
          Awaited<ReturnType<typeof oauthRedirect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthRedirect<TData = Awaited<ReturnType<typeof oauthRedirect>>, TError = void | ErrorResponse>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthRedirect>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Redirect to a social provider's consent screen
 */

export function useOauthRedirect<TData = Awaited<ReturnType<typeof oauthRedirect>>, TError = void | ErrorResponse>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthRedirect>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOauthRedirectQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary OAuth provider callback (redirects to the SPA with a handoff code)
 */
export const oauthCallback = (
    provider: string,
    params?: OauthCallbackParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/auth/oauth/${provider}/callback`, method: 'GET',
        params, signal
    },
      options);
    }




export const getOauthCallbackQueryKey = (provider: string,
    params?: OauthCallbackParams,) => {
    return [
    `/auth/oauth/${provider}/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getOauthCallbackQueryOptions = <TData = Awaited<ReturnType<typeof oauthCallback>>, TError = void>(provider: string,
    params?: OauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthCallbackQueryKey(provider,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof oauthCallback>>> = ({ signal }) => oauthCallback(provider,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oauthCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof oauthCallback>>>
export type OauthCallbackQueryError = void


export function useOauthCallback<TData = Awaited<ReturnType<typeof oauthCallback>>, TError = void>(
 provider: string,
    params: undefined |  OauthCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oauthCallback>>,
          TError,
          Awaited<ReturnType<typeof oauthCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallback<TData = Awaited<ReturnType<typeof oauthCallback>>, TError = void>(
 provider: string,
    params?: OauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oauthCallback>>,
          TError,
          Awaited<ReturnType<typeof oauthCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallback<TData = Awaited<ReturnType<typeof oauthCallback>>, TError = void>(
 provider: string,
    params?: OauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary OAuth provider callback (redirects to the SPA with a handoff code)
 */

export function useOauthCallback<TData = Awaited<ReturnType<typeof oauthCallback>>, TError = void>(
 provider: string,
    params?: OauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOauthCallbackQueryOptions(provider,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Exchange a handoff code for tokens
 */
export const oauthExchange = (
    oAuthExchangeRequest: OAuthExchangeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AuthResponse>(
      {url: `/auth/oauth/exchange`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: oAuthExchangeRequest, signal
    },
      options);
    }




export const getOauthExchangeQueryKey = (oAuthExchangeRequest?: OAuthExchangeRequest,) => {
    return [
    'POST', `/auth/oauth/exchange`, oAuthExchangeRequest
    ] as const;
    }


export const getOauthExchangeQueryOptions = <TData = Awaited<ReturnType<typeof oauthExchange>>, TError = ErrorResponse>(oAuthExchangeRequest: OAuthExchangeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthExchange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthExchangeQueryKey(oAuthExchangeRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof oauthExchange>>> = ({ signal }) => oauthExchange(oAuthExchangeRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oauthExchange>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthExchangeQueryResult = NonNullable<Awaited<ReturnType<typeof oauthExchange>>>
export type OauthExchangeQueryError = ErrorResponse


export function useOauthExchange<TData = Awaited<ReturnType<typeof oauthExchange>>, TError = ErrorResponse>(
 oAuthExchangeRequest: OAuthExchangeRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthExchange>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oauthExchange>>,
          TError,
          Awaited<ReturnType<typeof oauthExchange>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthExchange<TData = Awaited<ReturnType<typeof oauthExchange>>, TError = ErrorResponse>(
 oAuthExchangeRequest: OAuthExchangeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthExchange>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oauthExchange>>,
          TError,
          Awaited<ReturnType<typeof oauthExchange>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthExchange<TData = Awaited<ReturnType<typeof oauthExchange>>, TError = ErrorResponse>(
 oAuthExchangeRequest: OAuthExchangeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthExchange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Exchange a handoff code for tokens
 */

export function useOauthExchange<TData = Awaited<ReturnType<typeof oauthExchange>>, TError = ErrorResponse>(
 oAuthExchangeRequest: OAuthExchangeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oauthExchange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOauthExchangeQueryOptions(oAuthExchangeRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Current authenticated user
 */
export const getMe = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<User>(
      {url: `/auth/me`, method: 'GET', signal
    },
      options);
    }




export const getGetMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorResponse


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Current authenticated user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
