// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package adminapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// DubbingStudio defines model for DubbingStudio.
type DubbingStudio struct {
	Active  bool    `json:"active"`
	Id      int64   `json:"id"`
	Name    string  `json:"name"`
	SiteUrl *string `json:"site_url,omitempty"`
}

// DubbingStudioList defines model for DubbingStudioList.
type DubbingStudioList struct {
	Studios []DubbingStudio `json:"studios"`
}

// DubbingStudioRequest defines model for DubbingStudioRequest.
type DubbingStudioRequest struct {
	Active  *bool   `json:"active,omitempty"`
	Name    string  `json:"name"`
	SiteUrl *string `json:"site_url,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// CreateDubbingStudioJSONRequestBody defines body for CreateDubbingStudio for application/json ContentType.
type CreateDubbingStudioJSONRequestBody = DubbingStudioRequest

// UpdateDubbingStudioJSONRequestBody defines body for UpdateDubbingStudio for application/json ContentType.
type UpdateDubbingStudioJSONRequestBody = DubbingStudioRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListDubbingStudios List dubbing studios
	// (GET /admin/dubbing-studios)
	ListDubbingStudios(ctx echo.Context) error
	// CreateDubbingStudio Create a dubbing studio
	// (POST /admin/dubbing-studios)
	CreateDubbingStudio(ctx echo.Context) error
	// DeleteDubbingStudio Delete a dubbing studio
	// (DELETE /admin/dubbing-studios/{id})
	DeleteDubbingStudio(ctx echo.Context, id int64) error
	// UpdateDubbingStudio Update a dubbing studio
	// (PUT /admin/dubbing-studios/{id})
	UpdateDubbingStudio(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListDubbingStudios converts echo context to params.
func (w *ServerInterfaceWrapper) ListDubbingStudios(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDubbingStudios(ctx)
	return err
}

// CreateDubbingStudio converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDubbingStudio(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDubbingStudio(ctx)
	return err
}

// DeleteDubbingStudio converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDubbingStudio(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDubbingStudio(ctx, id)
	return err
}

// UpdateDubbingStudio converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDubbingStudio(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDubbingStudio(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/admin/dubbing-studios", wrapper.ListDubbingStudios, options.OperationMiddlewares["listDubbingStudios"]...)
	router.POST(options.BaseURL+"/admin/dubbing-studios", wrapper.CreateDubbingStudio, options.OperationMiddlewares["createDubbingStudio"]...)
	router.DELETE(options.BaseURL+"/admin/dubbing-studios/:id", wrapper.DeleteDubbingStudio, options.OperationMiddlewares["deleteDubbingStudio"]...)
	router.PUT(options.BaseURL+"/admin/dubbing-studios/:id", wrapper.UpdateDubbingStudio, options.OperationMiddlewares["updateDubbingStudio"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFXBbts4EP0VY3aPWkvZGHvQLZu0QNqiLZoWPQRGQYtjm4FFMsNRCsPgvxckLUeK1BpIk7Y3mkM/vnnv",
	"DbWDytTWaNTsoNwBobNGO4w/XhAZCovKaEbNYSms3ahKsDI6v3FGhz1XrbEWYfU34RJK+Cu/R81T1eUJ",
	"zXufgURXkbIBBEpoC9keKN590SwWSq+uuJHKhA1LxiKxStRExeoOw4q3FqGEhTEbFBp8BkqG/aWhWjCU",
	"oDT/N4OsPag04wopHNSi7kI4JqVXoeAU45eGNiNFnwHhbaMIJZTX4a49TtZymh+uMosbrDgA9rp5oxwP",
	"O3KxFpeKsXbH5OwL5A+XCiKxHfBs0Y+S+4C3DY7x+5HiTyBkhBhjdwhhn06NzokVHgduDw6xAz+sGlK8",
	"vQqiJuAFCkI6a3h9/+tlm6VXnz/CPqZRgli9z9aa2aaEK72MqWXFm1CRuLxam69uciZrpSdn7y8hgzsk",
	"l0agmJ5Mi9CtsaiFVVDC6bSYnkIGVvA6EstF+Gsuk1v/dPKywuhXkCcO5qWEEkLKes46yPrj/W9RPNlw",
	"DwM+MujvXocWZ8Xp99AO9PLOm9DUtaDtvqPJvv1J277PwBo30v85oWDsT0lKBjr+38jt8/Tezo/v55Cp",
	"QT/Q/+R5OIxpn+SQP2VAwpiIBybEU+PpzHdK+nCZxA0yDl26iPsPXbKCRI2M5KC83oEKDYQ5aN/aMr27",
	"fXmzjlRHH38/H5gxSzy7or01k/O9O1G32eN0S02O6JaBbUai+8lK8ftE+ZMGpPh1A9I+To/0OHk2Nhud",
	"z0w0rvuBuZ77uf8WAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
