/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Notifications API
 * OpenAPI spec version: 0.1.0
 */

export interface NotificationItem {
  id: number;
  type: string;
  status: string;
  read: boolean;
  payload: string;
  created_at: string;
}
