/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Notifications API
 * OpenAPI spec version: 0.1.0
 */

export interface NotificationItem {
  id: number;
  type: string;
  read: boolean;
  payload: string;
  created_at: string;
  /** User who triggered the notification (e.g. the follower for follow_request/follow_new/follow_accepted) */
  actor_id?: number;
}
