/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Notifications API
 * OpenAPI spec version: 0.1.0
 */

export interface RegisterDeviceTokenRequest {
  token: string;
  platform: string;
}
