/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Notifications API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  NotificationFeed,
  Prefs,
  TelegramLink,
  TelegramStatus,
  UpdatePrefsRequest
} from './model';

import { customInstance } from '../http';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary In-app notification feed
 */
export const listNotifications = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<NotificationFeed>(
      {url: `/me/notifications`, method: 'GET', signal
    },
      options);
    }




export const getListNotificationsQueryKey = () => {
    return [
    `/me/notifications`
    ] as const;
    }


export const getListNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotifications>>> = ({ signal }) => listNotifications(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof listNotifications>>>
export type ListNotificationsQueryError = ErrorResponse


export function useListNotifications<TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listNotifications>>,
          TError,
          Awaited<ReturnType<typeof listNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotifications<TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listNotifications>>,
          TError,
          Awaited<ReturnType<typeof listNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotifications<TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary In-app notification feed
 */

export function useListNotifications<TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListNotificationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Mark the whole feed as read
 */
export const markAllNotificationsRead = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/notifications/read-all`, method: 'POST', signal
    },
      options);
    }




export const getMarkAllNotificationsReadQueryKey = () => {
    return [
    'POST', `/me/notifications/read-all`
    ] as const;
    }


export const getMarkAllNotificationsReadQueryOptions = <TData = Awaited<ReturnType<typeof markAllNotificationsRead>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarkAllNotificationsReadQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof markAllNotificationsRead>>> = ({ signal }) => markAllNotificationsRead(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MarkAllNotificationsReadQueryResult = NonNullable<Awaited<ReturnType<typeof markAllNotificationsRead>>>
export type MarkAllNotificationsReadQueryError = unknown


export function useMarkAllNotificationsRead<TData = Awaited<ReturnType<typeof markAllNotificationsRead>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof markAllNotificationsRead>>,
          TError,
          Awaited<ReturnType<typeof markAllNotificationsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarkAllNotificationsRead<TData = Awaited<ReturnType<typeof markAllNotificationsRead>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof markAllNotificationsRead>>,
          TError,
          Awaited<ReturnType<typeof markAllNotificationsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarkAllNotificationsRead<TData = Awaited<ReturnType<typeof markAllNotificationsRead>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark the whole feed as read
 */

export function useMarkAllNotificationsRead<TData = Awaited<ReturnType<typeof markAllNotificationsRead>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMarkAllNotificationsReadQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Mark a single notification as read
 */
export const markNotificationRead = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/me/notifications/${id}/read`, method: 'POST', signal
    },
      options);
    }




export const getMarkNotificationReadQueryKey = (id: number,) => {
    return [
    'POST', `/me/notifications/${id}/read`
    ] as const;
    }


export const getMarkNotificationReadQueryOptions = <TData = Awaited<ReturnType<typeof markNotificationRead>>, TError = ErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarkNotificationReadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof markNotificationRead>>> = ({ signal }) => markNotificationRead(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MarkNotificationReadQueryResult = NonNullable<Awaited<ReturnType<typeof markNotificationRead>>>
export type MarkNotificationReadQueryError = ErrorResponse


export function useMarkNotificationRead<TData = Awaited<ReturnType<typeof markNotificationRead>>, TError = ErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof markNotificationRead>>,
          TError,
          Awaited<ReturnType<typeof markNotificationRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarkNotificationRead<TData = Awaited<ReturnType<typeof markNotificationRead>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof markNotificationRead>>,
          TError,
          Awaited<ReturnType<typeof markNotificationRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarkNotificationRead<TData = Awaited<ReturnType<typeof markNotificationRead>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark a single notification as read
 */

export function useMarkNotificationRead<TData = Awaited<ReturnType<typeof markNotificationRead>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMarkNotificationReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get notification preferences
 */
export const getPrefs = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Prefs>(
      {url: `/me/notifications/prefs`, method: 'GET', signal
    },
      options);
    }




export const getGetPrefsQueryKey = () => {
    return [
    `/me/notifications/prefs`
    ] as const;
    }


export const getGetPrefsQueryOptions = <TData = Awaited<ReturnType<typeof getPrefs>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrefs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrefsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrefs>>> = ({ signal }) => getPrefs(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrefs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrefsQueryResult = NonNullable<Awaited<ReturnType<typeof getPrefs>>>
export type GetPrefsQueryError = unknown


export function useGetPrefs<TData = Awaited<ReturnType<typeof getPrefs>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrefs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrefs>>,
          TError,
          Awaited<ReturnType<typeof getPrefs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrefs<TData = Awaited<ReturnType<typeof getPrefs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrefs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrefs>>,
          TError,
          Awaited<ReturnType<typeof getPrefs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrefs<TData = Awaited<ReturnType<typeof getPrefs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrefs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get notification preferences
 */

export function useGetPrefs<TData = Awaited<ReturnType<typeof getPrefs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrefs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPrefsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Update notification preferences
 */
export const updatePrefs = (
    updatePrefsRequest: UpdatePrefsRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Prefs>(
      {url: `/me/notifications/prefs`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePrefsRequest, signal
    },
      options);
    }




export const getUpdatePrefsQueryKey = (updatePrefsRequest?: UpdatePrefsRequest,) => {
    return [
    'PATCH', `/me/notifications/prefs`, updatePrefsRequest
    ] as const;
    }


export const getUpdatePrefsQueryOptions = <TData = Awaited<ReturnType<typeof updatePrefs>>, TError = unknown>(updatePrefsRequest: UpdatePrefsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePrefs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdatePrefsQueryKey(updatePrefsRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updatePrefs>>> = ({ signal }) => updatePrefs(updatePrefsRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updatePrefs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdatePrefsQueryResult = NonNullable<Awaited<ReturnType<typeof updatePrefs>>>
export type UpdatePrefsQueryError = unknown


export function useUpdatePrefs<TData = Awaited<ReturnType<typeof updatePrefs>>, TError = unknown>(
 updatePrefsRequest: UpdatePrefsRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePrefs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updatePrefs>>,
          TError,
          Awaited<ReturnType<typeof updatePrefs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdatePrefs<TData = Awaited<ReturnType<typeof updatePrefs>>, TError = unknown>(
 updatePrefsRequest: UpdatePrefsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePrefs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updatePrefs>>,
          TError,
          Awaited<ReturnType<typeof updatePrefs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdatePrefs<TData = Awaited<ReturnType<typeof updatePrefs>>, TError = unknown>(
 updatePrefsRequest: UpdatePrefsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePrefs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update notification preferences
 */

export function useUpdatePrefs<TData = Awaited<ReturnType<typeof updatePrefs>>, TError = unknown>(
 updatePrefsRequest: UpdatePrefsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePrefs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdatePrefsQueryOptions(updatePrefsRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Whether the user's Telegram account is linked
 */
export const getTelegramStatus = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TelegramStatus>(
      {url: `/me/telegram`, method: 'GET', signal
    },
      options);
    }




export const getGetTelegramStatusQueryKey = () => {
    return [
    `/me/telegram`
    ] as const;
    }


export const getGetTelegramStatusQueryOptions = <TData = Awaited<ReturnType<typeof getTelegramStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTelegramStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTelegramStatus>>> = ({ signal }) => getTelegramStatus(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTelegramStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTelegramStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getTelegramStatus>>>
export type GetTelegramStatusQueryError = unknown


export function useGetTelegramStatus<TData = Awaited<ReturnType<typeof getTelegramStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTelegramStatus>>,
          TError,
          Awaited<ReturnType<typeof getTelegramStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTelegramStatus<TData = Awaited<ReturnType<typeof getTelegramStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTelegramStatus>>,
          TError,
          Awaited<ReturnType<typeof getTelegramStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTelegramStatus<TData = Awaited<ReturnType<typeof getTelegramStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Whether the user's Telegram account is linked
 */

export function useGetTelegramStatus<TData = Awaited<ReturnType<typeof getTelegramStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTelegramStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Issue a one-time Telegram deep link
 */
export const getTelegramLink = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TelegramLink>(
      {url: `/me/telegram/link`, method: 'GET', signal
    },
      options);
    }




export const getGetTelegramLinkQueryKey = () => {
    return [
    `/me/telegram/link`
    ] as const;
    }


export const getGetTelegramLinkQueryOptions = <TData = Awaited<ReturnType<typeof getTelegramLink>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTelegramLinkQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTelegramLink>>> = ({ signal }) => getTelegramLink(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTelegramLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTelegramLinkQueryResult = NonNullable<Awaited<ReturnType<typeof getTelegramLink>>>
export type GetTelegramLinkQueryError = unknown


export function useGetTelegramLink<TData = Awaited<ReturnType<typeof getTelegramLink>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTelegramLink>>,
          TError,
          Awaited<ReturnType<typeof getTelegramLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTelegramLink<TData = Awaited<ReturnType<typeof getTelegramLink>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTelegramLink>>,
          TError,
          Awaited<ReturnType<typeof getTelegramLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTelegramLink<TData = Awaited<ReturnType<typeof getTelegramLink>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Issue a one-time Telegram deep link
 */

export function useGetTelegramLink<TData = Awaited<ReturnType<typeof getTelegramLink>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTelegramLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTelegramLinkQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
