// Package trackingapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package trackingapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AddLinkRequestKind.
const (
	AddLinkRequestKindDownload  AddLinkRequestKind = "download"
	AddLinkRequestKindImdb      AddLinkRequestKind = "imdb"
	AddLinkRequestKindKinopoisk AddLinkRequestKind = "kinopoisk"
	AddLinkRequestKindStreaming AddLinkRequestKind = "streaming"
	AddLinkRequestKindWiki      AddLinkRequestKind = "wiki"
)

// Valid indicates whether the value is a known member of the AddLinkRequestKind enum.
func (e AddLinkRequestKind) Valid() bool {
	switch e {
	case AddLinkRequestKindDownload:
		return true
	case AddLinkRequestKindImdb:
		return true
	case AddLinkRequestKindKinopoisk:
		return true
	case AddLinkRequestKindStreaming:
		return true
	case AddLinkRequestKindWiki:
		return true
	default:
		return false
	}
}

// Defines values for LinkKind.
const (
	LinkKindDownload  LinkKind = "download"
	LinkKindImdb      LinkKind = "imdb"
	LinkKindKinopoisk LinkKind = "kinopoisk"
	LinkKindStreaming LinkKind = "streaming"
	LinkKindWiki      LinkKind = "wiki"
)

// Valid indicates whether the value is a known member of the LinkKind enum.
func (e LinkKind) Valid() bool {
	switch e {
	case LinkKindDownload:
		return true
	case LinkKindImdb:
		return true
	case LinkKindKinopoisk:
		return true
	case LinkKindStreaming:
		return true
	case LinkKindWiki:
		return true
	default:
		return false
	}
}

// Defines values for ShowRefAiringStatus.
const (
	Airing         ShowRefAiringStatus = "airing"
	BetweenSeasons ShowRefAiringStatus = "between_seasons"
	Ended          ShowRefAiringStatus = "ended"
	NotStarted     ShowRefAiringStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ShowRefAiringStatus enum.
func (e ShowRefAiringStatus) Valid() bool {
	switch e {
	case Airing:
		return true
	case BetweenSeasons:
		return true
	case Ended:
		return true
	case NotStarted:
		return true
	default:
		return false
	}
}

// Defines values for UpdateShowRequestStatus.
const (
	UpdateShowRequestStatusCompleted   UpdateShowRequestStatus = "completed"
	UpdateShowRequestStatusDropped     UpdateShowRequestStatus = "dropped"
	UpdateShowRequestStatusOnHold      UpdateShowRequestStatus = "on_hold"
	UpdateShowRequestStatusPlanToWatch UpdateShowRequestStatus = "plan_to_watch"
	UpdateShowRequestStatusWatching    UpdateShowRequestStatus = "watching"
)

// Valid indicates whether the value is a known member of the UpdateShowRequestStatus enum.
func (e UpdateShowRequestStatus) Valid() bool {
	switch e {
	case UpdateShowRequestStatusCompleted:
		return true
	case UpdateShowRequestStatusDropped:
		return true
	case UpdateShowRequestStatusOnHold:
		return true
	case UpdateShowRequestStatusPlanToWatch:
		return true
	case UpdateShowRequestStatusWatching:
		return true
	default:
		return false
	}
}

// Defines values for UserShowStatus.
const (
	UserShowStatusCompleted   UserShowStatus = "completed"
	UserShowStatusDropped     UserShowStatus = "dropped"
	UserShowStatusOnHold      UserShowStatus = "on_hold"
	UserShowStatusPlanToWatch UserShowStatus = "plan_to_watch"
	UserShowStatusWatching    UserShowStatus = "watching"
)

// Valid indicates whether the value is a known member of the UserShowStatus enum.
func (e UserShowStatus) Valid() bool {
	switch e {
	case UserShowStatusCompleted:
		return true
	case UserShowStatusDropped:
		return true
	case UserShowStatusOnHold:
		return true
	case UserShowStatusPlanToWatch:
		return true
	case UserShowStatusWatching:
		return true
	default:
		return false
	}
}

// AddLinkRequest defines model for AddLinkRequest.
type AddLinkRequest struct {
	Kind  AddLinkRequestKind `json:"kind"`
	Label *string            `json:"label,omitempty"`
	Url   string             `json:"url"`
}

// AddLinkRequestKind defines model for AddLinkRequest.Kind.
type AddLinkRequestKind string

// AddShowRequest defines model for AddShowRequest.
type AddShowRequest struct {
	TmdbId int64 `json:"tmdb_id"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Link defines model for Link.
type Link struct {
	Id    int64    `json:"id"`
	Kind  LinkKind `json:"kind"`
	Label *string  `json:"label,omitempty"`
	Url   string   `json:"url"`
}

// LinkKind defines model for Link.Kind.
type LinkKind string

// LinkList defines model for LinkList.
type LinkList struct {
	Links []Link `json:"links"`
}

// Progress defines model for Progress.
type Progress struct {
	NextUnwatchedEpisodeId *int64 `json:"next_unwatched_episode_id,omitempty"`

	// Total Episodes with a known air date of today or earlier
	Total int `json:"total"`

	// Unwatched Aired but not-yet-watched episodes
	Unwatched int `json:"unwatched"`

	// Watched Watched episodes that have already aired
	Watched           int     `json:"watched"`
	WatchedEpisodeIds []int64 `json:"watched_episode_ids"`
}

// Settings defines model for Settings.
type Settings struct {
	IsPublic bool   `json:"is_public"`
	Timezone string `json:"timezone"`
}

// ShowRef defines model for ShowRef.
type ShowRef struct {
	AiringStatus       ShowRefAiringStatus `json:"airing_status"`
	Id                 int64               `json:"id"`
	NextEpisodeAirDate *string             `json:"next_episode_air_date,omitempty"`
	OriginalTitle      *string             `json:"original_title,omitempty"`
	PosterUrl          *string             `json:"poster_url,omitempty"`
	Title              string              `json:"title"`
	TmdbId             int64               `json:"tmdb_id"`
	VoteAverage        *float32            `json:"vote_average,omitempty"`
	VoteCount          *int64              `json:"vote_count,omitempty"`
}

// ShowRefAiringStatus defines model for ShowRef.AiringStatus.
type ShowRefAiringStatus string

// TrackedShow defines model for TrackedShow.
type TrackedShow struct {
	Progress Progress `json:"progress"`
	Show     ShowRef  `json:"show"`
	UserShow UserShow `json:"user_show"`
}

// TrackedShowList defines model for TrackedShowList.
type TrackedShowList struct {
	Tracked []TrackedShow `json:"tracked"`
}

// UpdateLinkRequest defines model for UpdateLinkRequest.
type UpdateLinkRequest struct {
	Url string `json:"url"`
}

// UpdateSettingsRequest defines model for UpdateSettingsRequest.
type UpdateSettingsRequest struct {
	IsPublic *bool  `json:"is_public,omitempty"`
	Timezone string `json:"timezone"`
}

// UpdateShowRequest defines model for UpdateShowRequest.
type UpdateShowRequest struct {
	Favorite         *bool                    `json:"favorite,omitempty"`
	PreferredDubbing *string                  `json:"preferred_dubbing,omitempty"`
	Status           *UpdateShowRequestStatus `json:"status,omitempty"`
}

// UpdateShowRequestStatus defines model for UpdateShowRequest.Status.
type UpdateShowRequestStatus string

// UserShow defines model for UserShow.
type UserShow struct {
	Favorite         bool           `json:"favorite"`
	Id               int64          `json:"id"`
	PreferredDubbing *string        `json:"preferred_dubbing,omitempty"`
	ShowId           int64          `json:"show_id"`
	Status           UserShowStatus `json:"status"`
}

// UserShowStatus defines model for UserShow.Status.
type UserShowStatus string

// EpisodeId defines model for EpisodeId.
type EpisodeId = int64

// ShowId defines model for ShowId.
type ShowId = int64

// ListTrackedParams defines parameters for ListTracked.
type ListTrackedParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = UpdateSettingsRequest

// AddShowJSONRequestBody defines body for AddShow for application/json ContentType.
type AddShowJSONRequestBody = AddShowRequest

// UpdateShowJSONRequestBody defines body for UpdateShow for application/json ContentType.
type UpdateShowJSONRequestBody = UpdateShowRequest

// AddLinkJSONRequestBody defines body for AddLink for application/json ContentType.
type AddLinkJSONRequestBody = AddLinkRequest

// UpdateLinkJSONRequestBody defines body for UpdateLink for application/json ContentType.
type UpdateLinkJSONRequestBody = UpdateLinkRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetSettings Get user settings
	// (GET /me/settings)
	GetSettings(ctx echo.Context) error
	// UpdateSettings Update user settings
	// (PATCH /me/settings)
	UpdateSettings(ctx echo.Context) error
	// ListTracked List the user's tracked shows with progress
	// (GET /me/shows)
	ListTracked(ctx echo.Context, params ListTrackedParams) error
	// AddShow Track a show (imports from TMDB on first use)
	// (POST /me/shows)
	AddShow(ctx echo.Context) error
	// RemoveShow Stop tracking a show
	// (DELETE /me/shows/{showId})
	RemoveShow(ctx echo.Context, showId ShowId) error
	// GetTracked One tracked show with progress
	// (GET /me/shows/{showId})
	GetTracked(ctx echo.Context, showId ShowId) error
	// UpdateShow Update status/favorite/dubbing
	// (PATCH /me/shows/{showId})
	UpdateShow(ctx echo.Context, showId ShowId) error
	// UnwatchEpisode Mark an episode unwatched
	// (DELETE /me/shows/{showId}/episodes/{episodeId}/watch)
	UnwatchEpisode(ctx echo.Context, showId ShowId, episodeId EpisodeId) error
	// WatchEpisode Mark an episode watched
	// (POST /me/shows/{showId}/episodes/{episodeId}/watch)
	WatchEpisode(ctx echo.Context, showId ShowId, episodeId EpisodeId) error
	// ListLinks List reference links
	// (GET /me/shows/{showId}/links)
	ListLinks(ctx echo.Context, showId ShowId) error
	// AddLink Add a reference link
	// (POST /me/shows/{showId}/links)
	AddLink(ctx echo.Context, showId ShowId) error
	// DeleteLink Delete a reference link
	// (DELETE /me/shows/{showId}/links/{linkId})
	DeleteLink(ctx echo.Context, showId ShowId, linkId int64) error
	// UpdateLink Update a reference link value (URL or plain text)
	// (PATCH /me/shows/{showId}/links/{linkId})
	UpdateLink(ctx echo.Context, showId ShowId, linkId int64) error
	// WatchShow Mark all catalogued episodes watched and set tracking status to completed
	// (POST /me/shows/{showId}/watch)
	WatchShow(ctx echo.Context, showId ShowId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSettings(ctx)
	return err
}

// UpdateSettings converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSettings(ctx)
	return err
}

// ListTracked converts echo context to params.
func (w *ServerInterfaceWrapper) ListTracked(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTrackedParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTracked(ctx, params)
	return err
}

// AddShow converts echo context to params.
func (w *ServerInterfaceWrapper) AddShow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddShow(ctx)
	return err
}

// RemoveShow converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveShow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveShow(ctx, showId)
	return err
}

// GetTracked converts echo context to params.
func (w *ServerInterfaceWrapper) GetTracked(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTracked(ctx, showId)
	return err
}

// UpdateShow converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateShow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateShow(ctx, showId)
	return err
}

// UnwatchEpisode converts echo context to params.
func (w *ServerInterfaceWrapper) UnwatchEpisode(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// ------------- Path parameter "episodeId" -------------
	var episodeId EpisodeId

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", ctx.Param("episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter episodeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnwatchEpisode(ctx, showId, episodeId)
	return err
}

// WatchEpisode converts echo context to params.
func (w *ServerInterfaceWrapper) WatchEpisode(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// ------------- Path parameter "episodeId" -------------
	var episodeId EpisodeId

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", ctx.Param("episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter episodeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.WatchEpisode(ctx, showId, episodeId)
	return err
}

// ListLinks converts echo context to params.
func (w *ServerInterfaceWrapper) ListLinks(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListLinks(ctx, showId)
	return err
}

// AddLink converts echo context to params.
func (w *ServerInterfaceWrapper) AddLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddLink(ctx, showId)
	return err
}

// DeleteLink converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// ------------- Path parameter "linkId" -------------
	var linkId int64

	err = runtime.BindStyledParameterWithOptions("simple", "linkId", ctx.Param("linkId"), &linkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter linkId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteLink(ctx, showId, linkId)
	return err
}

// UpdateLink converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateLink(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// ------------- Path parameter "linkId" -------------
	var linkId int64

	err = runtime.BindStyledParameterWithOptions("simple", "linkId", ctx.Param("linkId"), &linkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter linkId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateLink(ctx, showId, linkId)
	return err
}

// WatchShow converts echo context to params.
func (w *ServerInterfaceWrapper) WatchShow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "showId" -------------
	var showId ShowId

	err = runtime.BindStyledParameterWithOptions("simple", "showId", ctx.Param("showId"), &showId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter showId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.WatchShow(ctx, showId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/me/shows", wrapper.ListTracked, options.OperationMiddlewares["listTracked"]...)
	router.POST(options.BaseURL+"/me/shows", wrapper.AddShow, options.OperationMiddlewares["addShow"]...)
	router.DELETE(options.BaseURL+"/me/shows/:showId", wrapper.RemoveShow, options.OperationMiddlewares["removeShow"]...)
	router.GET(options.BaseURL+"/me/shows/:showId", wrapper.GetTracked, options.OperationMiddlewares["getTracked"]...)
	router.PATCH(options.BaseURL+"/me/shows/:showId", wrapper.UpdateShow, options.OperationMiddlewares["updateShow"]...)
	router.POST(options.BaseURL+"/me/shows/:showId/watch", wrapper.WatchShow, options.OperationMiddlewares["watchShow"]...)
	router.DELETE(options.BaseURL+"/me/shows/:showId/episodes/:episodeId/watch", wrapper.UnwatchEpisode, options.OperationMiddlewares["unwatchEpisode"]...)
	router.POST(options.BaseURL+"/me/shows/:showId/episodes/:episodeId/watch", wrapper.WatchEpisode, options.OperationMiddlewares["watchEpisode"]...)
	router.GET(options.BaseURL+"/me/shows/:showId/links", wrapper.ListLinks, options.OperationMiddlewares["listLinks"]...)
	router.POST(options.BaseURL+"/me/shows/:showId/links", wrapper.AddLink, options.OperationMiddlewares["addLink"]...)
	router.DELETE(options.BaseURL+"/me/shows/:showId/links/:linkId", wrapper.DeleteLink, options.OperationMiddlewares["deleteLink"]...)
	router.PATCH(options.BaseURL+"/me/shows/:showId/links/:linkId", wrapper.UpdateLink, options.OperationMiddlewares["updateLink"]...)
	router.GET(options.BaseURL+"/me/settings", wrapper.GetSettings, options.OperationMiddlewares["getSettings"]...)
	router.PATCH(options.BaseURL+"/me/settings", wrapper.UpdateSettings, options.OperationMiddlewares["updateSettings"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fltb9s4Ev4rBO+A6wFqnF6DA87f0vZ20d10WzQN+iEIBFoc26wlUiVHdr2B/vuCpN5sUX6JkyLAfkps",
	"U/PyzMwzw9E9TVSWKwkSDR3f05xplgGCdp/+nwujOLzn9oOQdExzhnMaUckyoGMKze8R1fC9EBo4HaMu",
	"IKImmUPG7INTpTOGdEyFxP9e0IjiOgf/EWagaVlG9HquVoNqjP/xNB2lfdzkShrwvmmttP0nURJBov2X",
	"5XkqEoZCydE3o6T9rtXxTw1TOqb/GLWQjfyvZuSlOS0cTKJFboXQMa1/qI11ui85vxJy8Rm+F2Cc5lyr",
	"HDQKb9tCSIcFyCKj41vK1UqmilkIDGpgmZAzGtGVWAgaUZHxCY3sQypXwizoXeO+QW2PlhFN2QRSK7P3",
	"S6FD35ddtG+9Rf5sK11NvkGCVsYl5zaCgw5hxiex4IdmQ1dz/WhIbRPDTW0ZGMNmsN+r+mBItg1QX/SB",
	"PkTPMISC02hfHK3TVyIUwVTIhUcAITP7ysGBVzYKmNZs3TPIiwyZ8UmrmQZj+mZI+IFxIVcMkznwuCKg",
	"odSSRZqySQo1X/TDhAqZw26rar1cQ1YC54SRhVQrSZjQhDMEoqYEFWdrojQBplMBOpgEjaF9DZcWBTIp",
	"kEiFL9eAL6ujpPLJBCUOyvu69TTBOUMyZ0sgLNXA+NqaD3yX1A6cm6E+IN93Rrq2usa7i0xYeygrrgFR",
	"yFkgK4SJ82KSiqRTBROlUmDS2SYy+FPJAwihORl1ZAZtcWw37ZvChBUcG2RYmC4BSIX2W43OZ3+MRnQC",
	"uAKQsQFmlLRBB8mBBwngYPJxVVLDyYSObda68gkXRKtCaTETkqUxCkwhSDa5Mgg6DnOOBXvowWOaQESX",
	"CiFmS9CbTC6LbNI5kKjCt+5j24pjw9qi2upoK3yhyH/RLFmAa3f96Ocd4trFjw3B2bmgkrTrfJ1ullMM",
	"6PiQZ24MaGfltuuthEp51Nq9x+Nwb0B/4ODu0IVwH3XUskOG3eQ2r3dOUgd1xqFu6OXXtDOo4/HZZ4cx",
	"u6asKVsqLRDCduQapqA18JgXk4nVHyrSPnE5evZkladMxqhi9xWNqJLxXKW2fmyUU/DcxrXK8yCFlSG/",
	"6jQ90p2DieRAv+dqdTg5PTVKPaaqzWtURy08/WyxFkJSaIHra1tzHs8JMA36ssB5++mX2tffvn6h1R3F",
	"Ae1+bX2fI+b+eiPkVDkEPc9TDlMbPkNcVQs5I5ef3tOILkEbP5qcn706O3fNJQfJckHH9PXZ+dlrCxXD",
	"ubNtlMHIdPr7DFx+23Rw1zF7N6S/AjYzwNZt7j/n5492l2t0BK5zH3/36BZZxvTa20QsoZLG+tK5lcz7",
	"9m/ySXWfBYNvFF8/mvVh0io3s8p2//K5QOgt3kaxjHxS2NwazAjbj6pu4rKpXV7cVpuE7wXodWeVUFdP",
	"68d29d09IS7brXQAnohenL8aktUYN+rsFhowrViCcw/nvwyp+idxOPrrTN4ZPuww14e1us4/UYZuLQsO",
	"Ss1Xj1cf7VjUw/6tBmbZ+cgA2NP/e1i4XEIQ5sJDXogsVxoNmWqVkS8f3r0hSpKp0MZxzL83i2J07/di",
	"pb8M2r7Sj+RnyNQSqmBu1UfI2vbIqFrJBerhon/9/EORt1V0Nh28RpX7JLStwTtqERsi+MFqfrC1T1K9",
	"uyr34mGp8FHCRrUGinVnWzk5xk/Wi44t9vOfUuwnhqvqWr6hjOphbFTPmOFSHdXrmdF9szsvR6s6rkNV",
	"fOO3JdVW6sFRjvaebBf+x5f9CVh+YHpBmKyXV6TdDg22qK9/K0AaOMJZ1SxnB4ekK3fiOZJqs3J+/BJ1",
	"s5C7/YFMgHiUdg09bm39zDh0613RT56W/CJ/z6T0wPBcck7YVnx2Zvjo3v7ZM/G8c9+fFMko+BbS6z7x",
	"LeRpw5T3LQDantngWaPxVGPH0VXzdHRezQrbcSNLlhZAXtx8viJKkzxlQhKEHzg06beTQk1hWy+VUGUi",
	"IUxyIjhkubKWn5FPGgzoJRgCP4Sx9+umsdhUkTPjHnHC3Qsuc0aaN2CMc+AElbtUJgxZqmYkZQiaMA1E",
	"KiSsQJUxFAlL03Xdq85oFGrZP/cqcvw97qSGnaY1QkX3VVz9Zs+CbADb65AfHi247Waw7G7vHDjdvd3t",
	"XXlX/hUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
