// Package showsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package showsapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ShowAiringStatus.
const (
	Airing         ShowAiringStatus = "airing"
	BetweenSeasons ShowAiringStatus = "between_seasons"
	Ended          ShowAiringStatus = "ended"
	NotStarted     ShowAiringStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ShowAiringStatus enum.
func (e ShowAiringStatus) Valid() bool {
	switch e {
	case Airing:
		return true
	case BetweenSeasons:
		return true
	case Ended:
		return true
	case NotStarted:
		return true
	default:
		return false
	}
}

// Episode defines model for Episode.
type Episode struct {
	AirDate       *string `json:"air_date,omitempty"`
	EpisodeNumber int     `json:"episode_number"`
	Id            int64   `json:"id"`
	Name          string  `json:"name"`
	Overview      *string `json:"overview,omitempty"`
	Runtime       *int    `json:"runtime,omitempty"`
	SeasonNumber  int     `json:"season_number"`
	StillUrl      *string `json:"still_url,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Genre defines model for Genre.
type Genre struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	TmdbId *int64 `json:"tmdb_id,omitempty"`
}

// ImportRequest defines model for ImportRequest.
type ImportRequest struct {
	TmdbId int64 `json:"tmdb_id"`
}

// Rating defines model for Rating.
type Rating struct {
	Source string `json:"source"`
	Value  string `json:"value"`
	Votes  *int64 `json:"votes,omitempty"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	Results []ShowSummary `json:"results"`
}

// Season defines model for Season.
type Season struct {
	AirDate      *string   `json:"air_date,omitempty"`
	EpisodeCount *int      `json:"episode_count,omitempty"`
	Episodes     []Episode `json:"episodes"`
	Id           int64     `json:"id"`
	Name         string    `json:"name"`
	Overview     *string   `json:"overview,omitempty"`
	PosterUrl    *string   `json:"poster_url,omitempty"`
	SeasonNumber int       `json:"season_number"`
}

// Show defines model for Show.
type Show struct {
	AiringStatus       ShowAiringStatus `json:"airing_status"`
	BackdropUrl        *string          `json:"backdrop_url,omitempty"`
	FirstAirDate       *string          `json:"first_air_date,omitempty"`
	Genres             *[]Genre         `json:"genres,omitempty"`
	Id                 int64            `json:"id"`
	InProduction       *bool            `json:"in_production,omitempty"`
	LastAirDate        *string          `json:"last_air_date,omitempty"`
	NextEpisodeAirDate *string          `json:"next_episode_air_date,omitempty"`
	OriginalLanguage   *string          `json:"original_language,omitempty"`
	OriginalTitle      *string          `json:"original_title,omitempty"`
	Overview           *string          `json:"overview,omitempty"`
	Popularity         *float32         `json:"popularity,omitempty"`
	PosterUrl          *string          `json:"poster_url,omitempty"`
	Ratings            *[]Rating        `json:"ratings,omitempty"`
	Seasons            *[]Season        `json:"seasons,omitempty"`
	Status             *string          `json:"status,omitempty"`
	Title              string           `json:"title"`
	TmdbId             int64            `json:"tmdb_id"`
	VoteAverage        *float32         `json:"vote_average,omitempty"`
	VoteCount          *int64           `json:"vote_count,omitempty"`
}

// ShowAiringStatus defines model for Show.AiringStatus.
type ShowAiringStatus string

// ShowList defines model for ShowList.
type ShowList struct {
	Shows []Show `json:"shows"`
}

// ShowSummary defines model for ShowSummary.
type ShowSummary struct {
	FirstAirDate  *string  `json:"first_air_date,omitempty"`
	OriginalTitle *string  `json:"original_title,omitempty"`
	Overview      *string  `json:"overview,omitempty"`
	Popularity    *float32 `json:"popularity,omitempty"`
	PosterUrl     *string  `json:"poster_url,omitempty"`
	Title         string   `json:"title"`
	TmdbId        int64    `json:"tmdb_id"`
	VoteAverage   *float32 `json:"vote_average,omitempty"`
	VoteCount     *int64   `json:"vote_count,omitempty"`
}

// ListShowsParams defines parameters for ListShows.
type ListShowsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// SearchShowsParams defines parameters for SearchShows.
type SearchShowsParams struct {
	Q string `form:"q" json:"q"`
}

// ImportShowJSONRequestBody defines body for ImportShow for application/json ContentType.
type ImportShowJSONRequestBody = ImportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListShows List/search the local catalog
	// (GET /shows)
	ListShows(ctx echo.Context, params ListShowsParams) error
	// ImportShow Import a show from TMDB into the local catalog
	// (POST /shows/import)
	ImportShow(ctx echo.Context) error
	// SearchShows Search TMDB for shows to add
	// (GET /shows/search)
	SearchShows(ctx echo.Context, params SearchShowsParams) error
	// GetShow Local show detail
	// (GET /shows/{id})
	GetShow(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListShows converts echo context to params.
func (w *ServerInterfaceWrapper) ListShows(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListShowsParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListShows(ctx, params)
	return err
}

// ImportShow converts echo context to params.
func (w *ServerInterfaceWrapper) ImportShow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportShow(ctx)
	return err
}

// SearchShows converts echo context to params.
func (w *ServerInterfaceWrapper) SearchShows(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchShowsParams
	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchShows(ctx, params)
	return err
}

// GetShow converts echo context to params.
func (w *ServerInterfaceWrapper) GetShow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetShow(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/shows/search", wrapper.SearchShows, options.OperationMiddlewares["searchShows"]...)
	router.POST(options.BaseURL+"/shows/import", wrapper.ImportShow, options.OperationMiddlewares["importShow"]...)
	router.GET(options.BaseURL+"/shows", wrapper.ListShows, options.OperationMiddlewares["listShows"]...)
	router.GET(options.BaseURL+"/shows/:id", wrapper.GetShow, options.OperationMiddlewares["getShow"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FdLb+M2EP4rAtujEHt30x502+1jkT7QIlmghyAQaGlsc0uRzHAY1wj83wuSki1HVGznsYu92SI18818",
	"M99o7lmlG6MVKLKsuGcI1mhlIfz5BVGj/1FpRaDI/+TGSFFxElpNPlut/DNbLaHh/tf3CHNWsO8mO6uT",
	"eGon0dpms8lZDbZCYbwRVrDuIG8NRd9GWF2D/2lQG0ASERQXWNacwolyUvKZBFYQOsgZrQ2wgllCoRZs",
	"kzOIVkrlmhmEUNorQhEsAP0dUfvnc40Np3jy4znLExcVb6BnYudF3wHeCVglD9EpEs1jcHsuLHCr1aNw",
	"LQkpS4cy4c27g1snEGpWXPvIHpocpKQN62aLRs8+Q0Xe05b+fQIasJYv4LD77mLK9kdQmCD3+VxQU8/K",
	"I82k0jWajYvGaKRLuHVgaYj8GX67V1NeLzn5wAburHZYpTNwx6UbOdEU3x4gPFSZDxC33jtfKeBXwLFa",
	"XoJ1MirLPn7cHQiCxh4Sj6ulXl25puG4DixHdxyRrwfoOtsjsFrRegFVqbSLojisz/bK8QF2ejcI7tUF",
	"ymhLgCOKcoQkHSM6AVkvK0lqlnqVJEaoRWmJkwsPQLnG+1Ga/FMk8A7jNZazGdAKQJURgfVOVQ395tqF",
	"NuPVvzVqMxr7XKCl8qTaWHhhO572qIPPIV2o0qCuXRWn6TaKmdYSuPJXJD81CgX/UdmV+UlvahQLobgs",
	"JVcLl54TvVskSD6pZo2THAWte8dttR0uaQyiejxJrQgnWOqq7GgZi/KTsrQt8OFIG83RKUMnyn/J7wD3",
	"WdmlLVzYitqTxmeHqEOdP2jgscb/Q6SGql3q1Wkz4uBwiCbHYHQjZoDkCUrwdWv8Gymah/UyJCZ0WeV8",
	"Hq480ZGPGXAEfO9oufv3a+f7t38+sXaZCEoYTndYlkQm7iFCzXUIKiaL1TD3VWCznzhxqRfZ+78v/FcO",
	"oI2ryvTszdk0MGdAcSNYwd6dTc/esZwZTssAbbKt2gWEnPg6CgvTRc0K5is9OAnvIG+AAC0rru+Z8C5u",
	"HeC6G5kFu+0i4akP7pt8f2N7O52+2L62bcvEyvbX7z4J59M3Y0a2qCa97a6lMcTaJ/D6xgdiu94LKZrY",
	"8AGZ0RIyqSsusypyEkzFHE9E+CYP3aptItfxmz3oQiw7sPRB1+sXy9H+UrDZr26vC5tXJuhlyMnZD9O3",
	"r0JlTFDGM09YNkfdZJ/+/PlDJhTpx7mN/I+2UdwvTmykfW6+WmPtrUZfvLui+0jDXGNgxmakM17XfQLu",
	"Rb0ZTf9H6NoqlXqvhbvMB3kfT/3hkXHzjTTR+fT8dfQw9EjooBqIC+kBb/4PAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
