/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Admin API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DubbingStudio,
  DubbingStudioList,
  DubbingStudioRequest,
  ErrorResponse,
  ListReportsParams,
  ReportList,
  ResolveReportRequest
} from './model';

import { customInstance } from '../http';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List dubbing studios
 */
export const listDubbingStudios = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DubbingStudioList>(
      {url: `/admin/dubbing-studios`, method: 'GET', signal
    },
      options);
    }




export const getListDubbingStudiosQueryKey = () => {
    return [
    `/admin/dubbing-studios`
    ] as const;
    }


export const getListDubbingStudiosQueryOptions = <TData = Awaited<ReturnType<typeof listDubbingStudios>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDubbingStudios>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDubbingStudiosQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDubbingStudios>>> = ({ signal }) => listDubbingStudios(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDubbingStudios>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDubbingStudiosQueryResult = NonNullable<Awaited<ReturnType<typeof listDubbingStudios>>>
export type ListDubbingStudiosQueryError = ErrorResponse


export function useListDubbingStudios<TData = Awaited<ReturnType<typeof listDubbingStudios>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDubbingStudios>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDubbingStudios>>,
          TError,
          Awaited<ReturnType<typeof listDubbingStudios>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDubbingStudios<TData = Awaited<ReturnType<typeof listDubbingStudios>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDubbingStudios>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDubbingStudios>>,
          TError,
          Awaited<ReturnType<typeof listDubbingStudios>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDubbingStudios<TData = Awaited<ReturnType<typeof listDubbingStudios>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDubbingStudios>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List dubbing studios
 */

export function useListDubbingStudios<TData = Awaited<ReturnType<typeof listDubbingStudios>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDubbingStudios>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDubbingStudiosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Create a dubbing studio
 */
export const createDubbingStudio = (
    dubbingStudioRequest: DubbingStudioRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DubbingStudio>(
      {url: `/admin/dubbing-studios`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dubbingStudioRequest, signal
    },
      options);
    }




export const getCreateDubbingStudioQueryKey = (dubbingStudioRequest?: DubbingStudioRequest,) => {
    return [
    'POST', `/admin/dubbing-studios`, dubbingStudioRequest
    ] as const;
    }


export const getCreateDubbingStudioQueryOptions = <TData = Awaited<ReturnType<typeof createDubbingStudio>>, TError = ErrorResponse>(dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateDubbingStudioQueryKey(dubbingStudioRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createDubbingStudio>>> = ({ signal }) => createDubbingStudio(dubbingStudioRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createDubbingStudio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateDubbingStudioQueryResult = NonNullable<Awaited<ReturnType<typeof createDubbingStudio>>>
export type CreateDubbingStudioQueryError = ErrorResponse


export function useCreateDubbingStudio<TData = Awaited<ReturnType<typeof createDubbingStudio>>, TError = ErrorResponse>(
 dubbingStudioRequest: DubbingStudioRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createDubbingStudio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createDubbingStudio>>,
          TError,
          Awaited<ReturnType<typeof createDubbingStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateDubbingStudio<TData = Awaited<ReturnType<typeof createDubbingStudio>>, TError = ErrorResponse>(
 dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createDubbingStudio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createDubbingStudio>>,
          TError,
          Awaited<ReturnType<typeof createDubbingStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateDubbingStudio<TData = Awaited<ReturnType<typeof createDubbingStudio>>, TError = ErrorResponse>(
 dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create a dubbing studio
 */

export function useCreateDubbingStudio<TData = Awaited<ReturnType<typeof createDubbingStudio>>, TError = ErrorResponse>(
 dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateDubbingStudioQueryOptions(dubbingStudioRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Update a dubbing studio
 */
export const updateDubbingStudio = (
    id: number,
    dubbingStudioRequest: DubbingStudioRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DubbingStudio>(
      {url: `/admin/dubbing-studios/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dubbingStudioRequest, signal
    },
      options);
    }




export const getUpdateDubbingStudioQueryKey = (id: number,
    dubbingStudioRequest?: DubbingStudioRequest,) => {
    return [
    'PUT', `/admin/dubbing-studios/${id}`, dubbingStudioRequest
    ] as const;
    }


export const getUpdateDubbingStudioQueryOptions = <TData = Awaited<ReturnType<typeof updateDubbingStudio>>, TError = ErrorResponse>(id: number,
    dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateDubbingStudioQueryKey(id,dubbingStudioRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateDubbingStudio>>> = ({ signal }) => updateDubbingStudio(id,dubbingStudioRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateDubbingStudio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateDubbingStudioQueryResult = NonNullable<Awaited<ReturnType<typeof updateDubbingStudio>>>
export type UpdateDubbingStudioQueryError = ErrorResponse


export function useUpdateDubbingStudio<TData = Awaited<ReturnType<typeof updateDubbingStudio>>, TError = ErrorResponse>(
 id: number,
    dubbingStudioRequest: DubbingStudioRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateDubbingStudio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateDubbingStudio>>,
          TError,
          Awaited<ReturnType<typeof updateDubbingStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateDubbingStudio<TData = Awaited<ReturnType<typeof updateDubbingStudio>>, TError = ErrorResponse>(
 id: number,
    dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateDubbingStudio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateDubbingStudio>>,
          TError,
          Awaited<ReturnType<typeof updateDubbingStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateDubbingStudio<TData = Awaited<ReturnType<typeof updateDubbingStudio>>, TError = ErrorResponse>(
 id: number,
    dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update a dubbing studio
 */

export function useUpdateDubbingStudio<TData = Awaited<ReturnType<typeof updateDubbingStudio>>, TError = ErrorResponse>(
 id: number,
    dubbingStudioRequest: DubbingStudioRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateDubbingStudioQueryOptions(id,dubbingStudioRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Delete a dubbing studio
 */
export const deleteDubbingStudio = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/admin/dubbing-studios/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteDubbingStudioQueryKey = (id: number,) => {
    return [
    'DELETE', `/admin/dubbing-studios/${id}`
    ] as const;
    }


export const getDeleteDubbingStudioQueryOptions = <TData = Awaited<ReturnType<typeof deleteDubbingStudio>>, TError = ErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteDubbingStudioQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteDubbingStudio>>> = ({ signal }) => deleteDubbingStudio(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteDubbingStudio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteDubbingStudioQueryResult = NonNullable<Awaited<ReturnType<typeof deleteDubbingStudio>>>
export type DeleteDubbingStudioQueryError = ErrorResponse


export function useDeleteDubbingStudio<TData = Awaited<ReturnType<typeof deleteDubbingStudio>>, TError = ErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteDubbingStudio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteDubbingStudio>>,
          TError,
          Awaited<ReturnType<typeof deleteDubbingStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteDubbingStudio<TData = Awaited<ReturnType<typeof deleteDubbingStudio>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteDubbingStudio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteDubbingStudio>>,
          TError,
          Awaited<ReturnType<typeof deleteDubbingStudio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteDubbingStudio<TData = Awaited<ReturnType<typeof deleteDubbingStudio>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete a dubbing studio
 */

export function useDeleteDubbingStudio<TData = Awaited<ReturnType<typeof deleteDubbingStudio>>, TError = ErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteDubbingStudio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteDubbingStudioQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary List moderation reports (optionally filtered by status)
 */
export const listReports = (
    params?: ListReportsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReportList>(
      {url: `/admin/reports`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListReportsQueryKey = (params?: ListReportsParams,) => {
    return [
    `/admin/reports`, ...(params ? [params] : [])
    ] as const;
    }


export const getListReportsQueryOptions = <TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorResponse>(params?: ListReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReportsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReports>>> = ({ signal }) => listReports(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReportsQueryResult = NonNullable<Awaited<ReturnType<typeof listReports>>>
export type ListReportsQueryError = ErrorResponse


export function useListReports<TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorResponse>(
 params: undefined |  ListReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReports>>,
          TError,
          Awaited<ReturnType<typeof listReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReports<TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorResponse>(
 params?: ListReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReports>>,
          TError,
          Awaited<ReturnType<typeof listReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReports<TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorResponse>(
 params?: ListReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List moderation reports (optionally filtered by status)
 */

export function useListReports<TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorResponse>(
 params?: ListReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Resolve or dismiss a moderation report
 */
export const resolveReport = (
    id: number,
    resolveReportRequest: ResolveReportRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/admin/reports/${id}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resolveReportRequest, signal
    },
      options);
    }




export const getResolveReportQueryKey = (id: number,
    resolveReportRequest?: ResolveReportRequest,) => {
    return [
    'POST', `/admin/reports/${id}/resolve`, resolveReportRequest
    ] as const;
    }


export const getResolveReportQueryOptions = <TData = Awaited<ReturnType<typeof resolveReport>>, TError = ErrorResponse>(id: number,
    resolveReportRequest: ResolveReportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveReportQueryKey(id,resolveReportRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveReport>>> = ({ signal }) => resolveReport(id,resolveReportRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resolveReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveReportQueryResult = NonNullable<Awaited<ReturnType<typeof resolveReport>>>
export type ResolveReportQueryError = ErrorResponse


export function useResolveReport<TData = Awaited<ReturnType<typeof resolveReport>>, TError = ErrorResponse>(
 id: number,
    resolveReportRequest: ResolveReportRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveReport>>,
          TError,
          Awaited<ReturnType<typeof resolveReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveReport<TData = Awaited<ReturnType<typeof resolveReport>>, TError = ErrorResponse>(
 id: number,
    resolveReportRequest: ResolveReportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveReport>>,
          TError,
          Awaited<ReturnType<typeof resolveReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveReport<TData = Awaited<ReturnType<typeof resolveReport>>, TError = ErrorResponse>(
 id: number,
    resolveReportRequest: ResolveReportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve or dismiss a moderation report
 */

export function useResolveReport<TData = Awaited<ReturnType<typeof resolveReport>>, TError = ErrorResponse>(
 id: number,
    resolveReportRequest: ResolveReportRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveReportQueryOptions(id,resolveReportRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
