/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Users API
 * OpenAPI spec version: 0.1.0
 */

export type ListUsersParams = {
/**
 * @maxLength 100
 */
q?: string;
/**
 * @minimum 1
 * @maximum 1000000
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
