/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Users API
 * OpenAPI spec version: 0.1.0
 */

export interface Progress {
  watched: number;
  total: number;
  /** @nullable */
  next_unwatched_episode_id?: number | null;
}
