/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Users API
 * OpenAPI spec version: 0.1.0
 */
import type { UserSummary } from './userSummary';

export interface UserList {
  total: number;
  page: number;
  page_size: number;
  users: UserSummary[];
}
