/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Users API
 * OpenAPI spec version: 0.1.0
 */

export interface UserProfile {
  id: number;
  display_name: string;
  is_public: boolean;
  shows_count: number;
}
