/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Catalog API
 * OpenAPI spec version: 0.1.0
 */
import type { ShowSummary } from './showSummary';

export interface DiscoveryResults {
  results: ShowSummary[];
  page: number;
  total_pages: number;
  total_results: number;
}
