/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Catalog API
 * OpenAPI spec version: 0.1.0
 */
import type { DiscoverShowsSort } from './discoverShowsSort';

export type DiscoverShowsParams = {
/**
 * @pattern ^[A-Z]{2}$
 */
country?: string;
/**
 * Genre IDs joined by commas (all) or pipes (any)
 */
genres?: string;
/**
 * @minimum 0
 * @maximum 10
 */
rating_min?: number;
/**
 * @minimum 0
 * @maximum 10
 */
rating_max?: number;
/**
 * @minimum 0
 */
votes_min?: number;
/**
 * First air date, YYYY-MM-DD
 */
date_from?: string;
/**
 * First air date, YYYY-MM-DD
 */
date_to?: string;
/**
 * @minimum 1
 * @maximum 500
 */
page?: number;
sort?: DiscoverShowsSort;
};
