/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Catalog API
 * OpenAPI spec version: 0.1.0
 */
import type { Episode } from './episode';

export interface Season {
  id: number;
  season_number: number;
  name: string;
  overview?: string;
  /** @nullable */
  air_date?: string | null;
  episode_count?: number;
  poster_url?: string;
  episodes: Episode[];
}
