/**
 * Generated by orval 🍺
 * Do not edit manually.
 * defShows Catalog API
 * OpenAPI spec version: 0.1.0
 */
import type { Genre } from './genre';
import type { Rating } from './rating';
import type { Season } from './season';
import type { ShowAiringStatus } from './showAiringStatus';

export interface Show {
  id: number;
  tmdb_id: number;
  title: string;
  original_title?: string;
  overview?: string;
  poster_url?: string;
  /** Automatically resolved IMDb title URL */
  imdb_url?: string;
  /** Wikipedia article, Russian preferred with English fallback */
  wikipedia_url?: string;
  backdrop_url?: string;
  status?: string;
  in_production?: boolean;
  /** @nullable */
  first_air_date?: string | null;
  /** @nullable */
  last_air_date?: string | null;
  /** @nullable */
  next_episode_air_date?: string | null;
  airing_status: ShowAiringStatus;
  original_language?: string;
  popularity?: number;
  vote_average?: number;
  vote_count?: number;
  genres?: Genre[];
  ratings?: Rating[];
  seasons?: Season[];
}
